import { TrainingStyle } from './types'

export type MovementPattern =
  | 'horizontal_push'
  | 'horizontal_pull'
  | 'vertical_push'
  | 'vertical_pull'
  | 'hip_hinge'
  | 'knee_dominant'
  | 'single_leg'
  | 'carry'
  | 'isolation_bicep'
  | 'isolation_tricep'
  | 'isolation_shoulder'
  | 'isolation_quad'
  | 'isolation_hamstring'
  | 'isolation_calf'
  | 'cardio'
  | 'core'
  | 'activation'

export type AngleVector = 'horizontal' | 'vertical' | 'diagonal' | 'rotational' | 'anti_extension' | 'anti_rotation' | 'lateral' | 'none'

export type MechanicsTier = 'tier1_compound' | 'tier2_compound' | 'tier3_isolation' | 'cardio' | 'primer'

export interface ExerciseEntry {
  name: string
  movement_pattern: MovementPattern
  mechanics_tier: MechanicsTier
  angle_vector: AngleVector
  primary_muscles: string[]
  equipment: string[]
  joint_stress: 'low' | 'moderate' | 'high'
  form_cues: string[]
  coach_note_swap?: string
  loads_joints: string[]
  style_tags: TrainingStyle[]
  substitution_group: string
  unilateral: boolean
  avg_duration_seconds: number
}

export const EXERCISE_DATABASE: ExerciseEntry[] = [
  // HORIZONTAL PUSH
  {
    name: 'Barbell Bench Press',
    movement_pattern: 'horizontal_push',
    mechanics_tier: 'tier1_compound',
    angle_vector: 'horizontal',
    primary_muscles: ['chest', 'anterior deltoid', 'triceps'],
    equipment: ['barbell', 'bench'],
    joint_stress: 'moderate',
    form_cues: ['Retract shoulder blades', 'Arch upper back slightly', 'Drive feet into floor', 'Touch chest at nipple line', 'Press up and slightly back'],
    coach_note_swap: 'The king of pressing movements for raw chest strength.',
    loads_joints: ['shoulder', 'wrist'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'bench_press',
    unilateral: false,
    avg_duration_seconds: 40,
  },
  {
    name: 'Dumbbell Bench Press',
    movement_pattern: 'horizontal_push',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'horizontal',
    primary_muscles: ['chest', 'anterior deltoid', 'triceps'],
    equipment: ['dumbbells', 'bench'],
    joint_stress: 'low',
    form_cues: ['Keep elbows at 45 degrees', 'Lower until stretch in pecs', 'Press dumbbells together at top', 'Control the eccentric phase'],
    coach_note_swap: 'Greater range of motion than barbell with less shoulder stress.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'bench_press',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Incline Dumbbell Press',
    movement_pattern: 'horizontal_push',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'diagonal',
    primary_muscles: ['upper chest', 'anterior deltoid', 'triceps'],
    equipment: ['dumbbells', 'incline bench'],
    joint_stress: 'low',
    form_cues: ['Set bench to 30-45 degrees', 'Drive through palms', 'Keep chest up', 'Lower to upper chest level'],
    coach_note_swap: 'Targets the clavicular head of the pec for upper chest development.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'bench_press',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Incline Machine Press',
    movement_pattern: 'horizontal_push',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'diagonal',
    primary_muscles: ['upper chest', 'anterior deltoid', 'triceps'],
    equipment: ['machine'],
    joint_stress: 'low',
    form_cues: ['Adjust seat so handles align with upper chest', 'Press forward, not up', 'Squeeze at peak contraction'],
    coach_note_swap: 'Machine-guided path reduces stabilizer fatigue for pure pressing volume.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'bench_press',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Cable Flyes',
    movement_pattern: 'horizontal_push',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'horizontal',
    primary_muscles: ['chest'],
    equipment: ['cable machine'],
    joint_stress: 'low',
    form_cues: ['Slight bend in elbows', 'Arc hands together', 'Squeeze at midline', 'Control the stretch'],
    coach_note_swap: 'Constant tension through the full range targets the pec fibers directly.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'fly_isolation',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Pec Deck Machine',
    movement_pattern: 'horizontal_push',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'horizontal',
    primary_muscles: ['chest'],
    equipment: ['machine'],
    joint_stress: 'low',
    form_cues: ['Sit with back flat against pad', 'Keep slight elbow bend', 'Squeeze pads together', 'Slow eccentric'],
    coach_note_swap: 'Guided isolation that removes coordination demands.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'fly_isolation',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Push-Ups',
    movement_pattern: 'horizontal_push',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'horizontal',
    primary_muscles: ['chest', 'anterior deltoid', 'triceps', 'core'],
    equipment: ['bodyweight'],
    joint_stress: 'low',
    form_cues: ['Hands shoulder-width', 'Body forms a straight line', 'Lower until chest near floor', 'Drive through palms'],
    coach_note_swap: 'Bodyweight pressing with natural scapular movement.',
    loads_joints: ['shoulder', 'wrist'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'bench_press',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Chest Dips',
    movement_pattern: 'horizontal_push',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['lower chest', 'triceps', 'anterior deltoid'],
    equipment: ['dip bars'],
    joint_stress: 'high',
    form_cues: ['Lean forward 30 degrees', 'Lower until stretch in chest', 'Elbows flare slightly', 'Drive up powerfully'],
    coach_note_swap: 'Heavy loaded stretch on the lower pecs and triceps.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'dip',
    unilateral: false,
    avg_duration_seconds: 35,
  },

  // HORIZONTAL PULL
  {
    name: 'Barbell Rows',
    movement_pattern: 'horizontal_pull',
    mechanics_tier: 'tier1_compound',
    angle_vector: 'horizontal',
    primary_muscles: ['lats', 'rhomboids', 'rear deltoid', 'biceps'],
    equipment: ['barbell'],
    joint_stress: 'moderate',
    form_cues: ['Hinge at hips 45 degrees', 'Pull to lower ribcage', 'Squeeze shoulder blades', 'Control the descent'],
    coach_note_swap: 'Heavy compound pulling for thick back development.',
    loads_joints: ['lower_back_axial', 'wrist'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'row',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Cable Rows',
    movement_pattern: 'horizontal_pull',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'horizontal',
    primary_muscles: ['lats', 'rhomboids', 'rear deltoid', 'biceps'],
    equipment: ['cable machine'],
    joint_stress: 'low',
    form_cues: ['Sit upright', 'Pull to navel', 'Squeeze shoulder blades together', 'Extend arms fully on eccentric'],
    coach_note_swap: 'Constant cable tension with adjustable angle.',
    loads_joints: [],
    style_tags: ['bodybuilding', 'functional', 'hybrid'],
    substitution_group: 'row',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Seated Cable Row',
    movement_pattern: 'horizontal_pull',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'horizontal',
    primary_muscles: ['lats', 'rhomboids', 'rear deltoid', 'biceps'],
    equipment: ['cable machine'],
    joint_stress: 'low',
    form_cues: ['Maintain upright torso', 'Pull handles to lower chest', 'Retract scapulae', 'Avoid using momentum'],
    coach_note_swap: 'Stable seated position isolates the back without lower-back fatigue.',
    loads_joints: [],
    style_tags: ['bodybuilding', 'functional', 'hybrid'],
    substitution_group: 'row',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Dumbbell Rows',
    movement_pattern: 'horizontal_pull',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'horizontal',
    primary_muscles: ['lats', 'rhomboids', 'biceps'],
    equipment: ['dumbbells', 'bench'],
    joint_stress: 'low',
    form_cues: ['Support on bench with one hand', 'Pull dumbbell to hip', 'Drive elbow past torso', 'Lower with control'],
    coach_note_swap: 'Unilateral pulling corrects imbalances with excellent lat stretch.',
    loads_joints: [],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'row',
    unilateral: true,
    avg_duration_seconds: 30,
  },
  {
    name: 'T-Bar Rows',
    movement_pattern: 'horizontal_pull',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'diagonal',
    primary_muscles: ['lats', 'rhomboids', 'rear deltoid', 'biceps'],
    equipment: ['t-bar', 'barbell'],
    joint_stress: 'moderate',
    form_cues: ['Straddle bar or use landmine', 'Hinge forward 45 degrees', 'Pull to chest', 'Squeeze at top'],
    coach_note_swap: 'Neutral grip row that loads the mid-back heavily.',
    loads_joints: ['lower_back_axial', 'wrist'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'row',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Face Pulls',
    movement_pattern: 'horizontal_pull',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'diagonal',
    primary_muscles: ['rear deltoid', 'rotator cuff', 'rhomboids'],
    equipment: ['cable machine'],
    joint_stress: 'low',
    form_cues: ['Set cable at face height', 'Pull rope to ears', 'Externally rotate at end', 'Squeeze rear delts'],
    coach_note_swap: 'Critical for shoulder health and rear delt/rotator cuff strength.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'functional', 'hybrid'],
    substitution_group: 'rear_delt',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Reverse Pec Deck',
    movement_pattern: 'horizontal_pull',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'horizontal',
    primary_muscles: ['rear deltoid', 'rhomboids'],
    equipment: ['machine'],
    joint_stress: 'low',
    form_cues: ['Face the pad', 'Slight elbow bend', 'Open arms wide', 'Squeeze rear delts at peak'],
    coach_note_swap: 'Machine-guided rear delt isolation for balanced shoulder development.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'rear_delt',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Rear Delt Flyes',
    movement_pattern: 'horizontal_pull',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'lateral',
    primary_muscles: ['rear deltoid'],
    equipment: ['dumbbells'],
    joint_stress: 'low',
    form_cues: ['Bend at hips', 'Arms hang below', 'Raise to sides', 'Squeeze rear delts at top'],
    coach_note_swap: 'Free-weight rear delt isolation for posture balance.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'rear_delt',
    unilateral: false,
    avg_duration_seconds: 28,
  },

  // VERTICAL PULL
  {
    name: 'Lat Pulldown',
    movement_pattern: 'vertical_pull',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['lats', 'biceps', 'teres major'],
    equipment: ['cable machine'],
    joint_stress: 'low',
    form_cues: ['Grip slightly wider than shoulders', 'Pull to upper chest', 'Lead with elbows', 'Lean back slightly'],
    coach_note_swap: 'Scalable vertical pulling for lat width development.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'functional', 'hybrid'],
    substitution_group: 'vertical_pull',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Pull-Ups',
    movement_pattern: 'vertical_pull',
    mechanics_tier: 'tier1_compound',
    angle_vector: 'vertical',
    primary_muscles: ['lats', 'biceps', 'teres major', 'core'],
    equipment: ['pull-up bar'],
    joint_stress: 'moderate',
    form_cues: ['Grip shoulder-width or wider', 'Dead hang start', 'Pull chin over bar', 'Control the descent'],
    coach_note_swap: 'The gold standard for relative upper-body pulling strength.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'vertical_pull',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Pull-Ups (Assisted)',
    movement_pattern: 'vertical_pull',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['lats', 'biceps', 'teres major'],
    equipment: ['assisted pull-up machine'],
    joint_stress: 'low',
    form_cues: ['Same form as regular pull-up', 'Select appropriate counterweight', 'Full range of motion'],
    coach_note_swap: 'Builds pulling strength progressively toward unassisted pull-ups.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'functional', 'hybrid'],
    substitution_group: 'vertical_pull',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Close-Grip Lat Pulldown',
    movement_pattern: 'vertical_pull',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['lats', 'biceps', 'rhomboids'],
    equipment: ['cable machine'],
    joint_stress: 'low',
    form_cues: ['Use V-bar or neutral grip handle', 'Pull to sternum', 'Squeeze lats at bottom', 'Full stretch at top'],
    coach_note_swap: 'Neutral grip shifts emphasis to lower lats and rhomboids.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'functional', 'hybrid'],
    substitution_group: 'row',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Straight-Arm Pulldown',
    movement_pattern: 'vertical_pull',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'diagonal',
    primary_muscles: ['lats', 'teres major'],
    equipment: ['cable machine'],
    joint_stress: 'low',
    form_cues: ['Stand back from cable', 'Arms nearly straight', 'Push bar down in arc to thighs', 'Squeeze lats at bottom'],
    coach_note_swap: 'Isolates the lats without bicep involvement.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'lat_isolation',
    unilateral: false,
    avg_duration_seconds: 28,
  },

  // VERTICAL PUSH
  {
    name: 'Overhead Press',
    movement_pattern: 'vertical_push',
    mechanics_tier: 'tier1_compound',
    angle_vector: 'vertical',
    primary_muscles: ['anterior deltoid', 'lateral deltoid', 'triceps', 'core'],
    equipment: ['barbell'],
    joint_stress: 'moderate',
    form_cues: ['Bar at collarbone height', 'Press straight up', 'Move head through at top', 'Brace core throughout'],
    coach_note_swap: 'Foundational overhead strength builder.',
    loads_joints: ['lower_back_axial', 'shoulder', 'wrist', 'neck'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'overhead_press',
    unilateral: false,
    avg_duration_seconds: 38,
  },
  {
    name: 'Dumbbell Shoulder Press',
    movement_pattern: 'vertical_push',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['anterior deltoid', 'lateral deltoid', 'triceps'],
    equipment: ['dumbbells'],
    joint_stress: 'low',
    form_cues: ['Start at ear height', 'Press up and slightly in', 'Lock out at top', 'Control the descent'],
    coach_note_swap: 'Freer path than barbell — better for shoulders with mobility limitations.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'overhead_press',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Arnold Press',
    movement_pattern: 'vertical_push',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'rotational',
    primary_muscles: ['anterior deltoid', 'lateral deltoid', 'triceps'],
    equipment: ['dumbbells'],
    joint_stress: 'low',
    form_cues: ['Start palms facing you', 'Rotate as you press up', 'Finish palms forward', 'Reverse on descent'],
    coach_note_swap: 'Rotational path hits all three delt heads through one rep.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'functional', 'hybrid'],
    substitution_group: 'overhead_press',
    unilateral: true,
    avg_duration_seconds: 35,
  },
  {
    name: 'Lateral Raises',
    movement_pattern: 'isolation_shoulder',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'lateral',
    primary_muscles: ['lateral deltoid'],
    equipment: ['dumbbells'],
    joint_stress: 'low',
    form_cues: ['Slight elbow bend', 'Raise to shoulder height', 'Lead with elbows', 'Slow eccentric'],
    coach_note_swap: 'Targets the medial delt for wider shoulders.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'lateral_delt',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Cable Lateral Raises',
    movement_pattern: 'isolation_shoulder',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'lateral',
    primary_muscles: ['lateral deltoid'],
    equipment: ['cable machine'],
    joint_stress: 'low',
    form_cues: ['Stand sideways to cable', 'Raise arm to shoulder height', 'Constant tension throughout', 'Control both phases'],
    coach_note_swap: 'Continuous cable tension eliminates the dead zone at the bottom.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'lateral_delt',
    unilateral: true,
    avg_duration_seconds: 28,
  },
  {
    name: 'Shrugs',
    movement_pattern: 'isolation_shoulder',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'vertical',
    primary_muscles: ['upper trapezius'],
    equipment: ['barbell', 'dumbbells'],
    joint_stress: 'low',
    form_cues: ['Elevate shoulders straight up', 'Hold at top 1 second', 'Do not roll shoulders', 'Full depression at bottom'],
    coach_note_swap: 'Direct trap work for neck and yoke thickness.',
    loads_joints: ['neck', 'wrist'],
    style_tags: ['bodybuilding', 'functional', 'hybrid'],
    substitution_group: 'shrug',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Dumbbell Shrugs',
    movement_pattern: 'isolation_shoulder',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'vertical',
    primary_muscles: ['upper trapezius'],
    equipment: ['dumbbells'],
    joint_stress: 'low',
    form_cues: ['Arms at sides', 'Shrug straight up', 'Hold briefly', 'Control descent'],
    coach_note_swap: 'Neutral grip reduces wrist strain compared to barbell shrugs.',
    loads_joints: ['neck'],
    style_tags: ['bodybuilding', 'functional', 'hybrid'],
    substitution_group: 'shrug',
    unilateral: false,
    avg_duration_seconds: 28,
  },

  // HIP HINGE
  {
    name: 'Deadlifts',
    movement_pattern: 'hip_hinge',
    mechanics_tier: 'tier1_compound',
    angle_vector: 'vertical',
    primary_muscles: ['hamstrings', 'glutes', 'erectors', 'lats'],
    equipment: ['barbell'],
    joint_stress: 'high',
    form_cues: ['Bar over mid-foot', 'Hinge at hips', 'Neutral spine', 'Drive through heels', 'Lock out at top'],
    coach_note_swap: 'The ultimate posterior chain builder — maximum systemic load.',
    loads_joints: ['lower_back_axial', 'knee', 'wrist'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'hip_hinge',
    unilateral: false,
    avg_duration_seconds: 45,
  },
  {
    name: 'Trap Bar Deadlift',
    movement_pattern: 'hip_hinge',
    mechanics_tier: 'tier1_compound',
    angle_vector: 'vertical',
    primary_muscles: ['hamstrings', 'glutes', 'quads', 'erectors'],
    equipment: ['trap bar'],
    joint_stress: 'moderate',
    form_cues: ['Stand in center', 'Hinge and grip handles', 'Neutral spine', 'Stand up powerfully'],
    coach_note_swap: 'Reduces lower-back shear while maintaining heavy hip-hinge loading.',
    loads_joints: ['lower_back_axial', 'knee'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'hip_hinge',
    unilateral: false,
    avg_duration_seconds: 40,
  },
  {
    name: 'Romanian Deadlifts',
    movement_pattern: 'hip_hinge',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['hamstrings', 'glutes', 'erectors'],
    equipment: ['barbell', 'dumbbells'],
    joint_stress: 'moderate',
    form_cues: ['Soft knees', 'Push hips back', 'Bar slides down thighs', 'Stop at mid-shin', 'Squeeze glutes up'],
    coach_note_swap: 'Eccentric-focused hamstring builder with excellent stretch.',
    loads_joints: ['lower_back_axial', 'wrist'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'hip_hinge',
    unilateral: false,
    avg_duration_seconds: 38,
  },
  {
    name: 'Good Mornings',
    movement_pattern: 'hip_hinge',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'horizontal',
    primary_muscles: ['hamstrings', 'glutes', 'erectors'],
    equipment: ['barbell'],
    joint_stress: 'moderate',
    form_cues: ['Bar on upper traps', 'Push hips back', 'Torso parallel to floor', 'Drive hips forward to stand'],
    coach_note_swap: 'A classic posterior chain builder that strengthens the hip hinge pattern under load.',
    loads_joints: ['lower_back_axial'],
    style_tags: ['bodybuilding', 'functional', 'hybrid'],
    substitution_group: 'hip_hinge',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Kettlebell Swing (Heavy)',
    movement_pattern: 'hip_hinge',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'diagonal',
    primary_muscles: ['glutes', 'hamstrings', 'core'],
    equipment: ['kettlebell'],
    joint_stress: 'low',
    form_cues: ['Hinge explosively', 'Snap hips forward', 'Float bell to chest height', 'Brace at top'],
    coach_note_swap: 'Ballistic hinge for power endurance and posterior chain conditioning.',
    loads_joints: ['lower_back_axial'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'hip_hinge',
    unilateral: false,
    avg_duration_seconds: 25,
  },
  {
    name: 'Lying Leg Curl',
    movement_pattern: 'isolation_hamstring',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'horizontal',
    primary_muscles: ['hamstrings'],
    equipment: ['machine'],
    joint_stress: 'low',
    form_cues: ['Pad above ankles', 'Curl heels toward glutes', 'Squeeze at top', 'Slow negative'],
    coach_note_swap: 'Isolated knee-flexion work for hamstring hypertrophy.',
    loads_joints: ['knee'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'leg_curl',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Nordic Hamstring Curl',
    movement_pattern: 'isolation_hamstring',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['hamstrings'],
    equipment: ['bodyweight'],
    joint_stress: 'moderate',
    form_cues: ['Kneel with ankles anchored', 'Lower torso forward slowly', 'Resist with hamstrings', 'Push off floor to return'],
    coach_note_swap: 'Eccentric hamstring strength — reduces injury risk significantly.',
    loads_joints: ['knee'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'leg_curl',
    unilateral: false,
    avg_duration_seconds: 30,
  },

  // KNEE DOMINANT
  {
    name: 'Barbell Squats',
    movement_pattern: 'knee_dominant',
    mechanics_tier: 'tier1_compound',
    angle_vector: 'vertical',
    primary_muscles: ['quadriceps', 'glutes', 'hamstrings', 'core'],
    equipment: ['barbell', 'squat rack'],
    joint_stress: 'high',
    form_cues: ['Bar on upper traps', 'Break at hips and knees', 'Knees track over toes', 'Depth to parallel or below', 'Drive up through heels'],
    coach_note_swap: 'The foundational lower body strength exercise.',
    loads_joints: ['lower_back_axial', 'knee', 'wrist'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'squat',
    unilateral: false,
    avg_duration_seconds: 42,
  },
  {
    name: 'Leg Press',
    movement_pattern: 'knee_dominant',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'diagonal',
    primary_muscles: ['quadriceps', 'glutes'],
    equipment: ['leg press machine'],
    joint_stress: 'moderate',
    form_cues: ['Feet shoulder-width on platform', 'Lower until 90-degree knee angle', 'Do not lock knees at top', 'Keep lower back pressed into seat'],
    coach_note_swap: 'Heavy quad loading without spinal compression.',
    loads_joints: ['knee'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'squat',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Goblet Squats',
    movement_pattern: 'knee_dominant',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['quadriceps', 'glutes', 'core'],
    equipment: ['dumbbell', 'kettlebell'],
    joint_stress: 'low',
    form_cues: ['Hold weight at chest', 'Elbows between knees at bottom', 'Upright torso', 'Full depth'],
    coach_note_swap: 'Teaches squat mechanics with natural upright posture.',
    loads_joints: ['knee'],
    style_tags: ['bodybuilding', 'functional', 'hybrid'],
    substitution_group: 'squat',
    unilateral: false,
    avg_duration_seconds: 32,
  },
  {
    name: 'Hack Squat',
    movement_pattern: 'knee_dominant',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'diagonal',
    primary_muscles: ['quadriceps', 'glutes'],
    equipment: ['hack squat machine'],
    joint_stress: 'moderate',
    form_cues: ['Shoulder pads secure', 'Feet lower on platform for quad emphasis', 'Full depth', 'Drive through heels'],
    coach_note_swap: 'Machine-guided squat that isolates quads with back support.',
    loads_joints: ['knee'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'squat',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Leg Extensions',
    movement_pattern: 'isolation_quad',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'horizontal',
    primary_muscles: ['quadriceps'],
    equipment: ['machine'],
    joint_stress: 'moderate',
    form_cues: ['Pad above ankles', 'Extend fully', 'Squeeze at top', 'Control the descent'],
    coach_note_swap: 'Open-chain quad isolation for targeted hypertrophy.',
    loads_joints: ['knee'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'quad_isolation',
    unilateral: false,
    avg_duration_seconds: 28,
  },

  // SINGLE LEG
  {
    name: 'Walking Lunges',
    movement_pattern: 'single_leg',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: ['dumbbells', 'bodyweight'],
    joint_stress: 'moderate',
    form_cues: ['Long stride', 'Back knee near floor', 'Upright torso', 'Push off front heel'],
    coach_note_swap: 'Dynamic unilateral work building balance and single-leg strength.',
    loads_joints: ['knee'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'single_leg',
    unilateral: true,
    avg_duration_seconds: 35,
  },
  {
    name: 'Bulgarian Split Squats',
    movement_pattern: 'single_leg',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: ['dumbbells', 'bench'],
    joint_stress: 'moderate',
    form_cues: ['Rear foot on bench', 'Lower until front thigh is parallel', 'Lean slightly forward', 'Drive up through front heel'],
    coach_note_swap: 'Unilateral knee-dominant with excellent quad stretch and balance demand.',
    loads_joints: ['knee'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'single_leg',
    unilateral: true,
    avg_duration_seconds: 38,
  },
  {
    name: 'Step-Ups',
    movement_pattern: 'single_leg',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['quadriceps', 'glutes'],
    equipment: ['dumbbells', 'box'],
    joint_stress: 'low',
    form_cues: ['Box at knee height', 'Drive through front heel', 'Stand fully at top', 'Lower with control'],
    coach_note_swap: 'Low-impact unilateral leg work emphasizing glute drive.',
    loads_joints: ['knee'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'single_leg',
    unilateral: true,
    avg_duration_seconds: 32,
  },

  // CARRY / LOADED CARRY
  {
    name: "Farmer's Walk",
    movement_pattern: 'carry',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'none',
    primary_muscles: ['forearms', 'traps', 'core', 'glutes'],
    equipment: ['dumbbells', 'farmer handles'],
    joint_stress: 'low',
    form_cues: ['Heavy weight in each hand', 'Tall posture', 'Short quick steps', 'Brace core throughout'],
    coach_note_swap: 'Total-body bracing exercise that builds grip, traps, and core stability.',
    loads_joints: ['wrist'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'carry',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Suitcase Carry',
    movement_pattern: 'carry',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'lateral',
    primary_muscles: ['obliques', 'core', 'forearms', 'traps'],
    equipment: ['dumbbell', 'kettlebell'],
    joint_stress: 'low',
    form_cues: ['Heavy weight in one hand only', 'Resist lateral lean', 'Walk tall and straight', 'Switch sides'],
    coach_note_swap: 'Anti-lateral flexion carry that hammers obliques and stabilizers.',
    loads_joints: ['wrist'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'carry',
    unilateral: true,
    avg_duration_seconds: 35,
  },
  {
    name: 'Overhead Carry',
    movement_pattern: 'carry',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['shoulders', 'core', 'traps', 'serratus anterior'],
    equipment: ['dumbbell', 'kettlebell'],
    joint_stress: 'moderate',
    form_cues: ['Lock weight overhead', 'Ribs down, core braced', 'Walk with control', 'Maintain vertical arm'],
    coach_note_swap: 'Overhead stability carry that builds shoulder health and core anti-extension.',
    loads_joints: ['shoulder'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'carry',
    unilateral: true,
    avg_duration_seconds: 35,
  },
  {
    name: 'Trap Bar Carry',
    movement_pattern: 'carry',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'none',
    primary_muscles: ['forearms', 'traps', 'core', 'glutes', 'quads'],
    equipment: ['trap bar'],
    joint_stress: 'low',
    form_cues: ['Load heavy', 'Stand tall', 'Walk with short controlled steps', 'Maintain neutral spine'],
    coach_note_swap: 'Highest-load carry variation for total-body strength and grip endurance.',
    loads_joints: ['wrist'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'carry',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Loaded Backpack Walk',
    movement_pattern: 'carry',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'none',
    primary_muscles: ['traps', 'core', 'glutes', 'legs'],
    equipment: ['bodyweight'],
    joint_stress: 'low',
    form_cues: ['Load weight onto a backpack evenly', 'Stand tall with chest up', 'Walk with controlled steps', 'Brace core throughout', 'Complete duration before switching load distribution'],
    coach_note_swap: 'Bodyweight-compatible carry using a weighted backpack or heavy backpack. Great for combating time-crunched scenarios.',
    loads_joints: [],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'carry',
    unilateral: false,
    avg_duration_seconds: 40,
  },
  {
    name: 'Farmer Squat Hold (Isometric Carry)',
    movement_pattern: 'carry',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'none',
    primary_muscles: ['core', 'legs', 'glutes', 'traps'],
    equipment: ['bodyweight'],
    joint_stress: 'low',
    form_cues: ['Stand at rest position or partial squat', 'Brace core maximally', 'Maintain stable posture', 'Breathe steadily under tension'],
    coach_note_swap: 'Isometric carry that builds anti-gravity stability. Perfect for bodyweight-only environments when hold duration matters more than movement.',
    loads_joints: [],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'carry',
    unilateral: false,
    avg_duration_seconds: 45,
  },

  // CALF
  {
    name: 'Calf Raises',
    movement_pattern: 'isolation_calf',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'vertical',
    primary_muscles: ['gastrocnemius', 'soleus'],
    equipment: ['machine', 'bodyweight'],
    joint_stress: 'low',
    form_cues: ['Full range of motion', 'Pause at the top', 'Stretch at the bottom', 'Straight legs'],
    coach_note_swap: 'Standing variation emphasizes the gastrocnemius.',
    loads_joints: [],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'calf',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Seated Calf Raises',
    movement_pattern: 'isolation_calf',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'vertical',
    primary_muscles: ['soleus'],
    equipment: ['machine'],
    joint_stress: 'low',
    form_cues: ['Knees bent at 90 degrees', 'Full range of motion', 'Slow eccentrics', 'Pause at peak'],
    coach_note_swap: 'Bent-knee position isolates the deeper soleus muscle.',
    loads_joints: [],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'calf',
    unilateral: false,
    avg_duration_seconds: 28,
  },

  // BICEPS
  {
    name: 'Barbell Curls',
    movement_pattern: 'isolation_bicep',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'vertical',
    primary_muscles: ['biceps brachii'],
    equipment: ['barbell'],
    joint_stress: 'low',
    form_cues: ['Elbows pinned to sides', 'Full extension at bottom', 'Squeeze at top', 'No swinging'],
    coach_note_swap: 'The classic mass builder for biceps.',
    loads_joints: ['wrist'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'bicep_curl',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Dumbbell Curls',
    movement_pattern: 'isolation_bicep',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'vertical',
    primary_muscles: ['biceps brachii'],
    equipment: ['dumbbells'],
    joint_stress: 'low',
    form_cues: ['Supinate as you curl', 'Elbows stable', 'Full range', 'Alternate or simultaneous'],
    coach_note_swap: 'Free-wrist supination for peak bicep contraction.',
    loads_joints: [],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'bicep_curl',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Hammer Curls',
    movement_pattern: 'isolation_bicep',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'vertical',
    primary_muscles: ['brachioradialis', 'biceps brachii'],
    equipment: ['dumbbells'],
    joint_stress: 'low',
    form_cues: ['Neutral grip (palms facing)', 'Curl to shoulder', 'No wrist rotation', 'Elbows stay put'],
    coach_note_swap: 'Targets brachioradialis and forearm thickness.',
    loads_joints: [],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'bicep_curl',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Cable Curls',
    movement_pattern: 'isolation_bicep',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'diagonal',
    primary_muscles: ['biceps brachii'],
    equipment: ['cable machine'],
    joint_stress: 'low',
    form_cues: ['Low cable attachment', 'Curl with constant tension', 'Squeeze at top', 'Slow negative'],
    coach_note_swap: 'Continuous tension throughout the entire curl arc.',
    loads_joints: [],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'bicep_curl',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Incline Dumbbell Curls',
    movement_pattern: 'isolation_bicep',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'diagonal',
    primary_muscles: ['biceps brachii (long head)'],
    equipment: ['dumbbells', 'incline bench'],
    joint_stress: 'low',
    form_cues: ['Lie on incline bench', 'Arms hang behind torso', 'Curl without swinging', 'Maximum stretch at bottom'],
    coach_note_swap: 'Incline angle pre-stretches the long head for superior activation.',
    loads_joints: [],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'bicep_curl',
    unilateral: true,
    avg_duration_seconds: 30,
  },

  // TRICEPS
  {
    name: 'Tricep Dips',
    movement_pattern: 'isolation_tricep',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['triceps', 'chest', 'anterior deltoid'],
    equipment: ['dip bars'],
    joint_stress: 'moderate',
    form_cues: ['Upright torso (more tricep)', 'Lower until 90-degree elbow', 'Lock out at top', 'Elbows close to body'],
    coach_note_swap: 'Heavy bodyweight tricep loading with pressing crossover.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'dip',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Tricep Pushdowns',
    movement_pattern: 'isolation_tricep',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'vertical',
    primary_muscles: ['triceps'],
    equipment: ['cable machine'],
    joint_stress: 'low',
    form_cues: ['Elbows pinned to sides', 'Push down to full extension', 'Squeeze at bottom', 'Control the return'],
    coach_note_swap: 'Cable isolation for tricep lateral head emphasis.',
    loads_joints: [],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'tricep_extension',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Overhead Tricep Extension',
    movement_pattern: 'isolation_tricep',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'vertical',
    primary_muscles: ['triceps (long head)'],
    equipment: ['dumbbell', 'cable machine'],
    joint_stress: 'low',
    form_cues: ['Elbows pointing up', 'Lower behind head', 'Extend fully overhead', 'Keep upper arms still'],
    coach_note_swap: 'Overhead position maximally stretches the long head.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'tricep_extension',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Skull Crushers',
    movement_pattern: 'isolation_tricep',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'horizontal',
    primary_muscles: ['triceps'],
    equipment: ['barbell', 'EZ bar'],
    joint_stress: 'moderate',
    form_cues: ['Lie flat on bench', 'Lower bar to forehead', 'Elbows point to ceiling', 'Extend without flaring'],
    coach_note_swap: 'Effective heavy tricep isolation with stretch component.',
    loads_joints: ['wrist', 'shoulder'],
    style_tags: ['bodybuilding', 'hybrid'],
    substitution_group: 'tricep_extension',
    unilateral: false,
    avg_duration_seconds: 30,
  },

  // CARDIO
  {
    name: 'Treadmill Intervals',
    movement_pattern: 'cardio',
    mechanics_tier: 'cardio',
    angle_vector: 'none',
    primary_muscles: ['cardiovascular system', 'quadriceps', 'hamstrings'],
    equipment: ['treadmill'],
    joint_stress: 'moderate',
    form_cues: ['Alternate sprint and recovery', 'Maintain upright posture', 'Pump arms', 'Land midfoot'],
    coach_note_swap: 'High-intensity intervals for maximum VO2max improvement.',
    loads_joints: ['knee'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'cardio_running',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Cycling Intervals',
    movement_pattern: 'cardio',
    mechanics_tier: 'cardio',
    angle_vector: 'none',
    primary_muscles: ['cardiovascular system', 'quadriceps'],
    equipment: ['stationary bike'],
    joint_stress: 'low',
    form_cues: ['Alternate resistance levels', 'Keep cadence above 80rpm', 'Seated and standing mix'],
    coach_note_swap: 'Low-impact cardio preserving knee and ankle joints.',
    loads_joints: ['knee'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'cardio_cycling',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Jump Rope',
    movement_pattern: 'cardio',
    mechanics_tier: 'cardio',
    angle_vector: 'none',
    primary_muscles: ['cardiovascular system', 'calves', 'shoulders'],
    equipment: ['jump rope'],
    joint_stress: 'moderate',
    form_cues: ['Wrists drive rotation', 'Light bounces', 'Stay on balls of feet', 'Keep elbows close'],
    coach_note_swap: 'Coordination + conditioning in one exercise.',
    loads_joints: ['knee', 'wrist'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'cardio_jump_rope',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Burpees',
    movement_pattern: 'cardio',
    mechanics_tier: 'cardio',
    angle_vector: 'none',
    primary_muscles: ['cardiovascular system', 'full body'],
    equipment: ['bodyweight'],
    joint_stress: 'high',
    form_cues: ['Squat down', 'Kick back to plank', 'Push-up', 'Jump up explosively'],
    coach_note_swap: 'Full-body metabolic conditioning at maximum intensity.',
    loads_joints: ['knee', 'wrist', 'shoulder'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'conditioning',
    unilateral: false,
    avg_duration_seconds: 20,
  },
  {
    name: 'Rowing Machine',
    movement_pattern: 'cardio',
    mechanics_tier: 'cardio',
    angle_vector: 'horizontal',
    primary_muscles: ['cardiovascular system', 'lats', 'legs'],
    equipment: ['rowing machine'],
    joint_stress: 'low',
    form_cues: ['Drive with legs first', 'Pull handle to lower chest', 'Reverse the sequence on return', 'Maintain rhythm'],
    coach_note_swap: 'Full-body low-impact cardio with significant posterior chain engagement.',
    loads_joints: [],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'cardio_rowing',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Elliptical',
    movement_pattern: 'cardio',
    mechanics_tier: 'cardio',
    angle_vector: 'none',
    primary_muscles: ['cardiovascular system', 'quadriceps', 'glutes'],
    equipment: ['elliptical machine'],
    joint_stress: 'low',
    form_cues: ['Upright posture', 'Push and pull handles', 'Vary resistance', 'Keep feet flat on pedals'],
    coach_note_swap: 'Zero-impact conditioning that spares knees and ankles.',
    loads_joints: [],
    style_tags: ['functional', 'hybrid'],
    substitution_group: 'cardio_elliptical',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Battle Ropes',
    movement_pattern: 'cardio',
    mechanics_tier: 'cardio',
    angle_vector: 'none',
    primary_muscles: ['cardiovascular system', 'shoulders', 'core'],
    equipment: ['battle ropes'],
    joint_stress: 'low',
    form_cues: ['Athletic stance', 'Alternate or simultaneous waves', 'Full arm range', 'Engage core throughout'],
    coach_note_swap: 'Upper-body dominant conditioning with core anti-extension.',
    loads_joints: ['shoulder'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'cardio_battle_ropes',
    unilateral: false,
    avg_duration_seconds: 25,
  },
  {
    name: 'Mountain Climbers',
    movement_pattern: 'cardio',
    mechanics_tier: 'cardio',
    angle_vector: 'none',
    primary_muscles: ['cardiovascular system', 'core', 'hip flexors'],
    equipment: ['bodyweight'],
    joint_stress: 'low',
    form_cues: ['Plank position', 'Drive knees toward chest', 'Keep hips level', 'Quick alternating rhythm'],
    coach_note_swap: 'Core-intensive cardio with zero equipment needed.',
    loads_joints: ['wrist'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'core_dynamic',
    unilateral: false,
    avg_duration_seconds: 20,
  },

  // CORE
  {
    name: 'Plank',
    movement_pattern: 'core',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'anti_extension',
    primary_muscles: ['rectus abdominis', 'transverse abdominis', 'obliques'],
    equipment: ['bodyweight'],
    joint_stress: 'low',
    form_cues: ['Elbows under shoulders', 'Body forms straight line', 'Squeeze glutes', 'Brace core', 'Breathe steadily'],
    coach_note_swap: 'Anti-extension hold building foundational core stability.',
    loads_joints: [],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'core_stability',
    unilateral: false,
    avg_duration_seconds: 60,
  },
  {
    name: 'Dead Bug',
    movement_pattern: 'core',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'anti_extension',
    primary_muscles: ['rectus abdominis', 'transverse abdominis'],
    equipment: ['bodyweight'],
    joint_stress: 'low',
    form_cues: ['Back flat on floor', 'Extend opposite arm and leg', 'Maintain low-back contact', 'Exhale on extension'],
    coach_note_swap: 'Teaches anti-extension with zero spinal load — excellent for back pain.',
    loads_joints: [],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'core_stability',
    unilateral: false,
    avg_duration_seconds: 45,
  },
  {
    name: 'Pallof Press',
    movement_pattern: 'core',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'anti_rotation',
    primary_muscles: ['obliques', 'transverse abdominis', 'core'],
    equipment: ['resistance band'],
    joint_stress: 'low',
    form_cues: ['Stand perpendicular to cable', 'Press hands straight out', 'Resist rotation', 'Hold 2 seconds extended'],
    coach_note_swap: 'Gold-standard anti-rotation exercise for rotational stability.',
    loads_joints: [],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'core_stability',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Hanging Leg Raises',
    movement_pattern: 'core',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'vertical',
    primary_muscles: ['rectus abdominis', 'hip flexors', 'obliques'],
    equipment: ['pull-up bar'],
    joint_stress: 'moderate',
    form_cues: ['Dead hang', 'Curl pelvis up', 'Raise legs to parallel or above', 'Control the descent'],
    coach_note_swap: 'Advanced core flexion under load — builds visible ab development.',
    loads_joints: ['shoulder'],
    style_tags: ['bodybuilding', 'functional', 'combat', 'hybrid'],
    substitution_group: 'core_dynamic',
    unilateral: false,
    avg_duration_seconds: 30,
  },
  {
    name: 'Ab Wheel Rollout',
    movement_pattern: 'core',
    mechanics_tier: 'tier2_compound',
    angle_vector: 'anti_extension',
    primary_muscles: ['rectus abdominis', 'transverse abdominis', 'lats'],
    equipment: ['ab wheel'],
    joint_stress: 'moderate',
    form_cues: ['Kneel with wheel below shoulders', 'Roll out maintaining neutral spine', 'Extend as far as possible', 'Pull back with abs'],
    coach_note_swap: 'Progressive anti-extension that challenges the entire anterior chain.',
    loads_joints: ['shoulder', 'wrist'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'core_stability',
    unilateral: false,
    avg_duration_seconds: 35,
  },
  {
    name: 'Cable Woodchops',
    movement_pattern: 'core',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'rotational',
    primary_muscles: ['obliques', 'core', 'shoulders'],
    equipment: ['cable machine'],
    joint_stress: 'low',
    form_cues: ['High-to-low or low-to-high path', 'Rotate through hips and torso', 'Arms stay extended', 'Control the return'],
    coach_note_swap: 'Rotational power for sport-specific core development.',
    loads_joints: [],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'core_rotational',
    unilateral: false,
    avg_duration_seconds: 28,
  },
  {
    name: 'Side Plank',
    movement_pattern: 'core',
    mechanics_tier: 'tier3_isolation',
    angle_vector: 'lateral',
    primary_muscles: ['obliques', 'quadratus lumborum', 'glute medius'],
    equipment: ['bodyweight'],
    joint_stress: 'low',
    form_cues: ['Elbow under shoulder', 'Hips stacked', 'Body forms straight line', 'Hold position steadily'],
    coach_note_swap: 'Anti-lateral flexion hold targeting oblique and hip stability.',
    loads_joints: [],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'core_stability',
    unilateral: true,
    avg_duration_seconds: 45,
  },

  // ACTIVATION / PRIMING
  {
    name: 'Box Jumps',
    movement_pattern: 'activation',
    mechanics_tier: 'primer',
    angle_vector: 'vertical',
    primary_muscles: ['glutes', 'quadriceps', 'calves'],
    equipment: ['plyo box'],
    joint_stress: 'moderate',
    form_cues: ['Athletic stance', 'Swing arms and explode up', 'Land softly with bent knees', 'Step down — do not jump down'],
    coach_note_swap: 'CNS primer that activates fast-twitch motor units for heavy lifting.',
    loads_joints: ['knee'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'explosive_lower',
    unilateral: false,
    avg_duration_seconds: 18,
  },
  {
    name: 'Band Pull-Aparts',
    movement_pattern: 'activation',
    mechanics_tier: 'primer',
    angle_vector: 'horizontal',
    primary_muscles: ['rear deltoid', 'rhomboids', 'rotator cuff'],
    equipment: ['resistance band'],
    joint_stress: 'low',
    form_cues: ['Arms straight at shoulder height', 'Pull band apart to chest', 'Squeeze shoulder blades', 'Controlled return'],
    coach_note_swap: 'Warms up the posterior shoulder complex and improves scapular positioning.',
    loads_joints: ['shoulder'],
    style_tags: ['functional', 'hybrid'],
    substitution_group: 'conditioning',
    unilateral: false,
    avg_duration_seconds: 18,
  },
  {
    name: 'Medicine Ball Slams',
    movement_pattern: 'activation',
    mechanics_tier: 'primer',
    angle_vector: 'vertical',
    primary_muscles: ['core', 'lats', 'shoulders', 'hip flexors'],
    equipment: ['medicine ball'],
    joint_stress: 'low',
    form_cues: ['Reach overhead fully', 'Slam with full-body extension', 'Hinge and follow through', 'Catch on bounce'],
    coach_note_swap: 'Full-body power primer that lights up the CNS before heavy compound work.',
    loads_joints: ['shoulder'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'explosive_upper',
    unilateral: false,
    avg_duration_seconds: 18,
  },
  {
    name: 'Broad Jumps',
    movement_pattern: 'activation',
    mechanics_tier: 'primer',
    angle_vector: 'horizontal',
    primary_muscles: ['glutes', 'hamstrings', 'quadriceps'],
    equipment: ['bodyweight'],
    joint_stress: 'moderate',
    form_cues: ['Hinge back at hips', 'Swing arms forward explosively', 'Jump for max distance', 'Stick the landing'],
    coach_note_swap: 'Horizontal power development primes hip extensors for hinge work.',
    loads_joints: ['knee'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'explosive_lower',
    unilateral: false,
    avg_duration_seconds: 15,
  },
  {
    name: 'Kettlebell Swings',
    movement_pattern: 'activation',
    mechanics_tier: 'primer',
    angle_vector: 'diagonal',
    primary_muscles: ['glutes', 'hamstrings', 'core', 'shoulders'],
    equipment: ['kettlebell'],
    joint_stress: 'low',
    form_cues: ['Hinge at hips', 'Snap hips forward', 'Float the bell to chest height', 'Brace core at the top'],
    coach_note_swap: 'Ballistic hip hinge that activates the posterior chain and elevates heart rate.',
    loads_joints: ['lower_back_axial'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'swing',
    unilateral: false,
    avg_duration_seconds: 20,
  },
  {
    name: 'Plyo Push-Ups',
    movement_pattern: 'activation',
    mechanics_tier: 'primer',
    angle_vector: 'horizontal',
    primary_muscles: ['chest', 'triceps', 'core'],
    equipment: ['bodyweight'],
    joint_stress: 'moderate',
    form_cues: ['Lower controlled', 'Explode off the ground', 'Hands leave floor', 'Land with soft elbows'],
    coach_note_swap: 'Upper-body power activation for pressing days.',
    loads_joints: ['wrist', 'shoulder'],
    style_tags: ['functional', 'combat', 'hybrid'],
    substitution_group: 'explosive_upper',
    unilateral: false,
    avg_duration_seconds: 18,
  },
]

export function getSmartReplacements(
  exerciseName: string,
  exclusions: string[] = []
): { exercise: ExerciseEntry; note: string }[] {
  const current = EXERCISE_DATABASE.find(
    e => e.name.toLowerCase() === exerciseName.toLowerCase()
  )
  if (!current) return []

  const excludedSet = new Set(exclusions.map(e => e.toLowerCase()))
  excludedSet.add(exerciseName.toLowerCase())

  const candidates = EXERCISE_DATABASE.filter(e => {
    if (excludedSet.has(e.name.toLowerCase())) return false
    if (e.movement_pattern !== current.movement_pattern) return false
    if (e.name === current.name) return false
    return true
  })

  const scored = candidates.map(candidate => {
    let score = 0
    if (candidate.mechanics_tier === current.mechanics_tier) score += 3
    if (candidate.joint_stress === current.joint_stress) score += 1
    if (candidate.joint_stress === 'low' && current.joint_stress !== 'low') score += 2
    const muscleOverlap = candidate.primary_muscles.filter(m =>
      current.primary_muscles.includes(m)
    ).length
    score += muscleOverlap

    let note = candidate.coach_note_swap || ''
    if (candidate.joint_stress === 'low' && current.joint_stress !== 'low') {
      note = `Lower joint stress alternative. ${note}`
    }

    return { exercise: candidate, score, note }
  })

  scored.sort((a, b) => b.score - a.score)
  return scored.slice(0, 5).map(({ exercise, note }) => ({ exercise, note }))
}

export function getExerciseEntry(name: string): ExerciseEntry | undefined {
  return EXERCISE_DATABASE.find(
    e => e.name.toLowerCase() === name.toLowerCase()
  )
}

// ---------------------------------------------------------------------------
// MOVEMENT FAMILIES
// ---------------------------------------------------------------------------
// `substitution_group` captures "these are interchangeable for the same slot".
// It does NOT capture "these are the same movement wearing different hats".
//
// Kettlebell Swings is classified as `activation` / group `swing`, while
// Kettlebell Swing (Heavy) is `hip_hinge` / group `hip_hinge`. Different
// pattern, different group — so nothing stopped the engine from programming
// both in one session. It is the same movement twice, and no trainer would
// write that.
//
// Anything not listed falls back to its substitution_group, so this map only
// needs to cover genuine cross-classification overlaps.

const MOVEMENT_FAMILIES: Record<string, string> = {
  'Kettlebell Swings': 'kettlebell_swing',
  'Kettlebell Swing (Heavy)': 'kettlebell_swing',
  'Chest Dips': 'dip',
  'Tricep Dips': 'dip',
  'Pull-Ups': 'pull_up',
  'Pull-Ups (Assisted)': 'pull_up',
  'Lat Pulldown': 'pulldown',
  'Close-Grip Lat Pulldown': 'pulldown',
  'Cable Rows': 'cable_row',
  'Seated Cable Row': 'cable_row',
  'Shrugs': 'shrug',
  'Dumbbell Shrugs': 'shrug',
  'Lateral Raises': 'lateral_raise',
  'Cable Lateral Raises': 'lateral_raise',
  'Calf Raises': 'calf_raise',
  'Seated Calf Raises': 'calf_raise',
  'Deadlifts': 'deadlift',
  'Trap Bar Deadlift': 'deadlift',
  'Box Jumps': 'jump',
  'Broad Jumps': 'jump',
  'Push-Ups': 'push_up',
  'Plyo Push-Ups': 'push_up',
}

/**
 * The dedup key for "is this the same movement as that one". Prefer this over
 * substitution_group when deciding whether two exercises can coexist in a
 * single session.
 */
export function getMovementFamily(entry: ExerciseEntry): string {
  return MOVEMENT_FAMILIES[entry.name] ?? entry.substitution_group
}
