import type { RawProposal } from './meal-generation'

// ---------------------------------------------------------------------------
// THE MEAL LIBRARY — original dishes, written for this app (30 Sep 2026).
//
// Ashley asked for hundreds more meals, and chose "write our own, and check
// them" over an open recipe dataset and over copying recipe sites
// (docs/plans/meal-library.md). Nothing here is copied from anywhere: the
// dishes are ordinary ones described in our own words.
//
// WHAT A DISH CARRIES: a slot, a name, a cuisine, a method and its ingredients
// in grams or counts, using only foods the app can cost. NO MACROS. Those are
// worked out per person when a dish is offered, by the same function every
// generated dish goes through, along with the diet check, the dislike filter
// and the scaling to the slot's budget. A dish that suits nobody's numbers is
// never served; the data cannot make the app less safe than a model does.
//
// THE METHOD NAMES NO AMOUNT: the app rescales every dish, and a method that
// says "add 2 tbsp" would contradict the list beside it (the 19 Sep rule).
// "Ready in N minutes" is fine; that is how the quick/standard band is read.
//
// CUISINE LABELS are the app's own (generate-meals' familiar and exotic lists),
// because the pool allows one exotic cuisine per meal and reads tags[0].
// ---------------------------------------------------------------------------

type Slot = 'breakfast' | 'lunch' | 'dinner' | 'snack'

const BRIT = 'British / Classic'
const ITAL = 'Italian'
const AMER = 'American / Diner Classic'
const MEXI = 'Mexican'
const MEDI = 'Mediterranean (Greek, Lebanese, Turkish)'
const THAI = 'Thai'
const MIDE = 'Middle Eastern (Persian, Moroccan)'
const KORE = 'Korean'
const INDI = 'Indian (North Indian, South Indian)'
const CARI = 'Caribbean (Jamaican, Cuban)'
const JAPA = 'Japanese'
const VIET = 'Vietnamese'
const ETHI = 'Ethiopian'
const SPAN = 'Spanish (Basque, Catalan)'
const BRAZ = 'Brazilian'
const WAFR = 'West African (Nigerian, Ghanaian)'
const PERU = 'Peruvian'
const FILI = 'Filipino'
const GEOR = 'Georgian'
const CAJU = 'Cajun / Creole'
const NORD = 'Scandinavian (Nordic)'

const d = (slot: Slot, name: string, cuisine: string, prep: string, ingredients: string[]): RawProposal =>
  ({ slot, name, cuisine, prep, ingredients })

const BREAKFASTS: RawProposal[] = [
  d('breakfast', 'Spinach and feta omelette', MEDI, 'Whisk the eggs and whites, cook in a hot oiled pan for a few minutes, scatter over the spinach and feta, fold and serve.', ['3 egg', '2 egg white', '60g spinach', '40g feta cheese', '1 tsp olive oil']),
  d('breakfast', 'Berry quark bowl with granola', BRIT, 'Spoon the quark into a bowl, top with the berries and granola and drizzle with honey. Ready in 5 minutes.', ['250g quark', '100g mixed berries', '30g granola', '1 tsp honey']),
  d('breakfast', 'Vanilla protein porridge', BRIT, 'Simmer the oats in the milk until thick, take off the heat and stir in the protein powder and vanilla. Top with banana slices.', ['45g oats', '200ml milk semi skimmed', '30g whey protein powder', '100g greek yoghurt 0%', '100g blueberries', '1 tsp vanilla extract']),
  d('breakfast', 'Smoked salmon scramble on toast', BRIT, 'Scramble the eggs gently in butter, fold through the smoked salmon off the heat and pile onto toasted bread. Ready in 10 minutes.', ['3 egg', '100g smoked salmon', '1 slice wholemeal bread', '1 tsp butter']),
  d('breakfast', 'Huevos rancheros bowl', MEXI, 'Warm the beans with the salsa, fry the eggs, and serve over the warmed tortilla with sliced avocado.', ['2 egg', '100g egg white', '80g black beans', '80g salsa', '1 corn tortilla', '40g avocado']),
  d('breakfast', 'Turmeric tofu scramble', AMER, 'Crumble the tofu into a hot oiled pan with the turmeric, cook until golden, then wilt in the spinach and tomatoes and finish with nutritional yeast.', ['200g tofu firm', '1 tsp turmeric powder', '80g spinach', '60g cherry tomatoes', '1 tsp olive oil', '2 tbsp nutritional yeast']),
  d('breakfast', 'Cottage cheese and pineapple bowl', AMER, 'Spoon the cottage cheese into a bowl, top with pineapple and crushed almonds. Ready in 5 minutes.', ['250g cottage cheese', '100g pineapple', '15g almonds']),
  d('breakfast', 'Shakshuka with feta', MIDE, 'Soften the onion and pepper with the spices, add the tomatoes and simmer until thick, make wells for the eggs and cook until just set, then crumble over the feta.', ['2 egg', '100g turkey mince', '200g chopped tomatoes canned', '100g bell pepper', '60g onion', '1 tsp cumin', '1 tsp paprika', '30g feta cheese']),
  d('breakfast', 'Peanut butter overnight oats', BRIT, 'Stir the oats, yoghurt, protein powder and peanut butter together with a splash of milk, cover and chill overnight.', ['60g oats', '200g greek yoghurt 0%', '1 tbsp peanut butter', '30g whey protein powder']),
  d('breakfast', 'Turkey breakfast patties with eggs', AMER, 'Mix the turkey with the spinach and paprika, shape into patties and pan-fry until cooked through, then fry the eggs to serve on top.', ['150g turkey mince', '2 egg', '50g spinach', '1 tsp paprika', '1 tsp olive oil']),
  d('breakfast', 'Ham and cheddar egg muffins', AMER, 'Whisk the eggs with the chopped ham, cheese and spinach, pour into a muffin tin and bake until set.', ['3 egg', '60g ham', '30g cheddar cheese', '50g spinach']),
  d('breakfast', 'Banana protein pancakes', AMER, 'Blend the banana, eggs, oats and protein powder into a batter, cook small pancakes in a non-stick pan and serve with the yoghurt.', ['100g banana', '100g egg white', '1 egg', '40g oats', '30g whey protein powder', '100g greek yoghurt 0%']),
  d('breakfast', 'Avocado toast with egg and smoked salmon', AMER, 'Toast the bread, mash the avocado over it, top with smoked salmon and a poached egg. Ready in 10 minutes.', ['2 slices wholemeal bread', '2 egg', '30g avocado', '120g smoked salmon']),
  d('breakfast', 'Vanilla chia pudding with protein', BRIT, 'Whisk the chia seeds and protein powder into the soy milk, chill until set, and top with raspberries.', ['25g chia seeds', '250ml soy milk', '30g vegan protein powder', '100g raspberries']),
  d('breakfast', 'Mushroom and egg white frittata', ITAL, 'Soften the mushrooms in a pan, pour over the whisked eggs and whites, crumble in the feta and bake or grill until set.', ['3 egg', '4 egg white', '100g mushroom', '30g feta cheese', '1 tsp olive oil']),
  d('breakfast', 'Salmon and egg rice breakfast', JAPA, 'Flake the cooked salmon over the warm rice, top with a soft-cooked egg and wilted spinach and season with soy sauce and sesame oil.', ['180g salmon', '100g white rice cooked', '1 egg', '60g spinach', '1 tbsp soy sauce', '1 tsp sesame oil']),
  d('breakfast', 'Ham and egg breakfast burrito', MEXI, 'Scramble the eggs and whites, warm the tortilla, and roll up the eggs with the beans, cheese and salsa.', ['60g tortilla wrap', '2 egg', '150g egg white', '60g ham', '30g cheddar cheese', '50g salsa']),
  d('breakfast', 'Skyr and mango bowl', INDI, 'Spoon the skyr into a bowl, top with chopped mango, pistachios and a pinch of cinnamon. Ready in 5 minutes.', ['350g skyr', '150g mango', '20g pistachios', '1 tsp cinnamon']),
  d('breakfast', 'Masala omelette', INDI, 'Fry the onion and tomato with the garam masala, pour over the whisked eggs and whites with the spinach and cook until set.', ['3 egg', '2 egg white', '40g onion', '50g cherry tomatoes', '60g spinach', '1 tsp garam masala', '1 tsp vegetable oil']),
  d('breakfast', 'Gochujang egg and tofu rice bowl', KORE, 'Pan-fry the tofu, wilt the spinach, and layer both over the rice with a fried egg, finishing with gochujang and sesame oil.', ['100g brown rice cooked', '2 egg', '200g tofu firm', '80g spinach', '1 tbsp gochujang', '1 tsp sesame oil']),
  d('breakfast', 'Ricotta and egg toast with strawberries', ITAL, 'Toast the bread, spread with ricotta, top with a sliced boiled egg and serve with the strawberries alongside.', ['1 slice wholemeal bread', '60g ricotta cheese', '2 egg', '100g egg white', '100g strawberries']),
  d('breakfast', 'Tempeh and potato hash', AMER, 'Crumble the tempeh and fry with the diced potato, pepper and onion and the paprika until crisp at the edges.', ['250g tempeh', '80g potato boiled', '60g bell pepper', '40g onion', '1 tsp olive oil', '1 tsp paprika']),
  d('breakfast', 'Berry protein smoothie bowl', AMER, 'Blend the protein powder, banana, berries and yoghurt until thick, pour into a bowl and top with granola. Ready in 5 minutes.', ['30g whey protein powder', '100g banana', '150g mixed berries', '200g greek yoghurt 0%', '25g granola']),
  d('breakfast', 'Cottage cheese overnight oats', BRIT, 'Stir the oats, cottage cheese, milk and berries together, cover and chill overnight.', ['40g oats', '200g cottage cheese', '100ml milk semi skimmed', '100g blueberries', '30g whey protein powder']),
  d('breakfast', 'Smoked salmon and dill open sandwich', NORD, 'Spread the toasted bread with quark, top with smoked salmon and cucumber ribbons and finish with dill. Ready in 5 minutes.', ['2 slices wholemeal bread', '80g smoked salmon', '100g quark', '60g cucumber', '1 tsp dill']),
  d('breakfast', 'Turkish eggs with yoghurt', MEDI, 'Spoon the garlicky yoghurt onto a plate, top with poached eggs and a drizzle of paprika oil, and serve with toasted bread.', ['3 egg', '150g greek yoghurt 0%', '1 tsp paprika', '1 tsp olive oil', '1 slice wholemeal bread']),
  d('breakfast', 'Halloumi and mushroom scramble', BRIT, 'Fry the halloumi and mushrooms until golden, add the spinach, then stir through the softly scrambled eggs.', ['3 egg', '60g halloumi', '100g mushroom', '40g spinach', '1 tsp olive oil']),
  d('breakfast', 'Sweet potato and egg hash', AMER, 'Dice and fry the sweet potato until tender, stir in the spinach and top with fried eggs.', ['100g sweet potato baked', '2 egg', '100g egg white', '80g spinach', '1 tsp olive oil', '1 tsp paprika']),
  d('breakfast', 'Vegan protein pancakes with berries', AMER, 'Blend the banana, oats, protein powder and soy milk into a batter, cook small pancakes in a non-stick pan and serve with berries.', ['100g banana', '40g oats', '30g vegan protein powder', '100g tofu silken', '100ml soy milk', '100g mixed berries']),
  d('breakfast', 'Quinoa breakfast bowl', PERU, 'Warm the quinoa with cinnamon, stir in the protein powder, and top with yoghurt and blueberries.', ['150g quinoa cooked', '30g whey protein powder', '150g greek yoghurt 0%', '80g blueberries', '1 tsp cinnamon']),
  d('breakfast', 'Crab and avocado egg cups', AMER, 'Whisk the eggs with the flaked crab, pour into a greased muffin tin, bake until set and serve with sliced avocado.', ['3 egg', '80g crab meat', '50g avocado', '50g spinach']),
  d('breakfast', 'Tofu breakfast burrito', MEXI, 'Crumble and fry the tofu with turmeric until golden, warm the tortilla, and roll up with the beans, salsa and sliced avocado.', ['220g tofu firm', '50g tortilla wrap', '50g black beans', '60g salsa', '1 tsp turmeric powder']),
  d('breakfast', 'Soy yoghurt protein bowl', BRIT, 'Stir the protein powder through the soy yoghurt, top with blueberries and granola. Ready in 5 minutes.', ['250g soy yoghurt', '30g vegan protein powder', '100g blueberries', '25g granola']),
  d('breakfast', 'Soy milk protein oats', BRIT, 'Simmer the oats in the soy milk until creamy, stir in the protein powder and chia seeds and top with raspberries.', ['50g oats', '250ml soy milk', '30g vegan protein powder', '100g raspberries', '1 tbsp chia seeds']),
  d('breakfast', 'Paneer bhurji with spinach', INDI, 'Crumble the paneer into a pan with the eggs, garam masala and spinach and scramble until just set.', ['100g paneer', '2 egg', '100g egg white', '60g spinach', '1 tsp garam masala', '1 tsp vegetable oil']),
  d('breakfast', 'Spanish tortilla with ham and peppers', SPAN, 'Soften the potato and pepper in a little oil, pour over the whisked eggs and whites with the ham, and cook gently until set, flipping once.', ['3 egg', '100g egg white', '100g potato boiled', '60g ham', '60g bell pepper', '1 tsp olive oil']),
  d('breakfast', 'Brazilian eggs with black beans and kale', BRAZ, 'Garlicky kale and warm black beans alongside softly scrambled eggs and whites.', ['3 egg', '100g egg white', '80g black beans', '60g kale', '1 tsp olive oil']),
  d('breakfast', 'Georgian cheese and egg skillet', GEOR, 'Bubble the tomatoes in a pan, stir in the cheese, crack in the eggs and whites and cook until set, and serve with toast.', ['3 egg', '100g egg white', '40g sulguni cheese', '100g tomato', '1 slice wholemeal bread']),
  d('breakfast', 'Persian herb omelette', MIDE, 'Fold the spinach, coriander and dill into the whisked eggs and whites with crushed walnuts and cook slowly until set.', ['3 egg', '100g egg white', '60g spinach', '1 tsp coriander', '1 tsp dill', '20g walnuts']),
  d('breakfast', 'Tamago and tofu rice bowl', JAPA, 'Steam the rice, top with soft silken tofu and a rolled omelette, and finish with edamame and a splash of soy sauce.', ['2 egg', '150g tofu silken', '100g edamame', '100g white rice cooked', '1 tbsp soy sauce']),
  d('breakfast', 'Spiced callaloo-style eggs', CARI, 'Wilt the spinach and tomato with the jerk paste and scramble in the eggs and whites.', ['3 egg', '100g egg white', '100g spinach', '60g tomato', '1 tsp jerk seasoning paste']),
  d('breakfast', 'Berbere scrambled eggs with injera', ETHI, 'Scramble the eggs with berbere and tomato until soft, and serve with torn injera and cottage cheese.', ['3 egg', '60g injera flatbread', '1 tsp berbere spice mix', '60g tomato', '100g cottage cheese']),
]

const LUNCHES: RawProposal[] = [
  d('lunch', 'Chicken Caesar wrap', AMER, 'Slice the cooked chicken, toss with the yoghurt, mustard and parmesan, pile onto the salad leaves in a warm tortilla and roll tightly. Ready in 10 minutes.', ['160g chicken breast', '1 tortilla wrap', '60g mixed salad leaves', '20g parmesan', '60g greek yoghurt 0%', '1 tsp mustard']),
  d('lunch', 'Tuna and white bean salad', MEDI, 'Flake the tuna over the beans, tomatoes and rocket, then dress with olive oil and balsamic vinegar. Ready in 10 minutes.', ['150g tuna canned in water', '120g cannellini beans', '100g cherry tomatoes', '50g rocket', '1 tbsp olive oil', '1 tbsp balsamic vinegar']),
  d('lunch', 'Chicken burrito bowl', MEXI, 'Grill and slice the chicken, then build a bowl with the rice, warmed beans, sweetcorn, salsa and sliced avocado.', ['170g chicken breast', '120g brown rice cooked', '70g black beans', '80g salsa', '40g avocado', '50g sweetcorn']),
  d('lunch', 'Teriyaki salmon and edamame bowl', JAPA, 'Bake the salmon brushed with teriyaki sauce until just cooked, then serve over the rice with steamed broccoli and edamame.', ['150g salmon', '80g white rice cooked', '100g edamame', '100g broccoli', '1 tbsp teriyaki sauce']),
  d('lunch', 'Greek chicken pitta', MEDI, 'Grill the seasoned chicken, slice and stuff into a warm pitta with cucumber, tomato, tzatziki and crumbled feta. Ready in 15 minutes.', ['170g chicken breast', '1 pitta bread', '60g tzatziki', '80g cucumber', '60g tomato', '30g feta cheese']),
  d('lunch', 'Turkey and hummus wrap', MEDI, 'Spread the tortilla with hummus, layer the sliced turkey, salad leaves and cucumber, then roll tightly. Ready in 5 minutes.', ['150g turkey breast', '60g tortilla wrap', '40g hummus', '60g mixed salad leaves', '60g cucumber']),
  d('lunch', 'Prawn and avocado quinoa salad', AMER, 'Toss the warm prawns with the quinoa, leaves and tomatoes, top with sliced avocado and dress with olive oil and lime.', ['180g prawns', '100g quinoa cooked', '60g avocado', '80g mixed salad leaves', '100g cherry tomatoes', '1 tbsp olive oil', '20g lime']),
  d('lunch', 'Chicken, lentil and feta quinoa bowl', MEDI, 'Toss the warm lentils and quinoa with the cucumber, tomatoes and crumbled feta, and dress with olive oil.', ['100g lentils green', '80g quinoa cooked', '50g feta cheese', '100g cucumber', '100g cherry tomatoes', '100g chicken breast', '1 tsp olive oil']),
  d('lunch', 'Vietnamese chicken noodle salad', VIET, 'Toss the shredded chicken with the noodles, carrot, cucumber and sprouts, then dress with fish sauce, lime and coriander.', ['160g chicken breast', '100g rice noodles cooked', '60g carrot', '60g cucumber', '40g bean sprouts', '1 tbsp fish sauce', '20g lime', '1 tsp coriander']),
  d('lunch', 'Thai beef salad', THAI, 'Sear the steak, rest and slice it thinly, then toss with the cucumber, tomatoes and leaves in a dressing of fish sauce, lime and sweet chilli. Serve with a little rice.', ['170g beef steak sirloin', '100g cucumber', '100g cherry tomatoes', '60g mixed salad leaves', '1 tbsp fish sauce', '20g lime', '1 tbsp sweet chili sauce', '80g white rice cooked']),
  d('lunch', 'Tandoori-spiced tofu bowl', INDI, 'Marinate the tofu in soy yoghurt and garam masala, bake until golden and serve over the rice with cucumber and tomatoes.', ['200g tofu firm', '80g soy yoghurt', '1 tsp garam masala', '100g cucumber', '100g cherry tomatoes', '80g basmati rice cooked']),
  d('lunch', 'Chicken fajita bowl', MEXI, 'Fry the chicken strips with the peppers, onion and spices until charred, then serve over the rice with guacamole.', ['170g chicken breast', '100g bell pepper', '60g onion', '120g brown rice cooked', '50g guacamole', '1 tsp chili powder', '1 tsp cumin', '1 tsp olive oil']),
  d('lunch', 'Tuna nicoise', MEDI, 'Arrange the flaked tuna, halved boiled eggs, blanched green beans, potatoes and olives on a plate and dress with olive oil and mustard.', ['150g tuna canned in water', '2 egg', '100g green beans', '100g potato boiled', '30g olives', '1 tbsp olive oil', '1 tsp mustard']),
  d('lunch', 'Miso tofu noodle soup', JAPA, 'Simmer the water with the miso, add the mushrooms and bok choy, then the tofu and noodles and heat through. Ready in 15 minutes.', ['200g tofu firm', '100g rice noodles cooked', '1 tbsp miso paste', '100g bok choy', '60g mushroom', '300ml water']),
  d('lunch', 'Chicken and black bean quesadilla', MEXI, 'Fill the tortilla with shredded chicken, beans, peppers and cheese, fold and toast in a dry pan until crisp on both sides, then serve with salsa.', ['1 tortilla wrap', '140g chicken breast', '30g cheddar cheese', '60g black beans', '80g salsa', '60g bell pepper']),
  d('lunch', 'Turkey meatballs with marinara and pasta', ITAL, 'Mix the turkey with the egg and parmesan, roll into balls and bake, then simmer in the passata and serve over the pasta with wilted spinach.', ['170g turkey mince', '1 egg', '20g parmesan', '200g tomato passata', '100g wholewheat pasta cooked', '60g spinach']),
  d('lunch', 'Lemon chicken and couscous salad', MEDI, 'Grill the lemony chicken, slice and toss with the couscous, cucumber, tomatoes and feta, then dress with olive oil.', ['170g chicken breast', '100g couscous cooked', '100g cucumber', '100g cherry tomatoes', '1 tbsp olive oil', '30g feta cheese', '20g lemon']),
  d('lunch', 'Sardines on toast with tomato', NORD, 'Toast the bread, top with the sardines and sliced tomatoes, and serve with cucumber and a spoon of yoghurt. Ready in 10 minutes.', ['120g sardines canned', '2 slices wholemeal bread', '100g cherry tomatoes', '60g cucumber', '60g greek yoghurt 0%']),
  d('lunch', 'Crab and sweetcorn chowder', AMER, 'Soften the onion, add the potato and milk and simmer until the potato is tender, then stir in the sweetcorn and crab and heat through.', ['150g crab meat', '100g sweetcorn', '150g potato boiled', '250ml milk semi skimmed', '50g onion']),
  d('lunch', 'Bulgogi-style beef and broccoli bowl', KORE, 'Slice and sear the beef in soy sauce and sesame oil, steam the broccoli and carrot, and serve over the rice.', ['170g beef steak sirloin', '100g broccoli', '100g white rice cooked', '1 tbsp soy sauce', '1 tsp sesame oil', '60g carrot']),
  d('lunch', 'Prawn pad thai-style noodles', THAI, 'Stir-fry the prawns, then toss with the noodles, a scrambled egg, sprouts and a sauce of fish sauce, tamarind and lime, and finish with crushed peanuts.', ['180g prawns', '100g rice noodles cooked', '1 egg', '60g bean sprouts', '1 tbsp fish sauce', '20g lime', '1 tbsp tamarind paste', '15g peanuts']),
  d('lunch', 'Chicken adobo rice bowl', FILI, 'Simmer the chicken in soy sauce, vinegar and garlic until tender and glossy, and serve over the rice with green beans.', ['180g chicken thigh', '120g white rice cooked', '1 tbsp soy sauce', '1 tbsp rice vinegar', '2 cloves garlic', '100g green beans']),
  d('lunch', 'Peruvian chicken and quinoa salad', PERU, 'Rub the chicken with cumin and paprika, grill and slice, then toss with the quinoa, sweetcorn and tomatoes and finish with lime.', ['170g chicken breast', '120g quinoa cooked', '80g sweetcorn', '80g cherry tomatoes', '1 tsp cumin', '1 tsp paprika', '20g lime', '1 tsp olive oil']),
  d('lunch', 'Brazilian beef and black bean bowl', BRAZ, 'Brown the beef, warm the beans, and serve both over the rice with garlicky wilted kale.', ['150g beef mince 5% fat', '100g black beans', '100g white rice cooked', '60g kale', '1 tsp olive oil']),
  d('lunch', 'Berbere lentil and tofu bowl with injera', ETHI, 'Simmer the lentils with the berbere until soft, fry the tofu until golden, and serve with the cabbage and torn injera.', ['120g lentils red', '1 tsp berbere spice mix', '60g injera flatbread', '100g cabbage', '60g tomato', '150g tofu firm']),
  d('lunch', 'Georgian walnut chicken with green beans', GEOR, 'Poach the chicken, then coat in a sauce of ground walnuts, onion and coriander and serve with green beans and a little rice.', ['170g chicken breast', '30g walnuts', '60g onion', '1 tsp coriander', '120g green beans', '100g white rice cooked']),
  d('lunch', 'Jerk chicken with rice and peas', CARI, 'Coat the chicken in jerk paste and grill until charred, then serve with rice mixed with kidney beans and fresh pineapple.', ['170g chicken breast', '1 tbsp jerk seasoning paste', '100g white rice cooked', '80g kidney beans', '60g pineapple']),
  d('lunch', 'Suya-spiced beef and cabbage salad', WAFR, 'Rub the steak with suya spice, sear and slice it, then serve over shredded cabbage with tomato, onion and roasted sweet potato.', ['170g beef steak sirloin', '1 tbsp suya spice rub', '100g cherry tomatoes', '60g onion', '100g cabbage', '100g sweet potato baked']),
  d('lunch', 'Garlic prawns with white beans', SPAN, 'Sizzle the garlic and paprika in olive oil, add the prawns and beans, and wilt in the spinach at the end. Ready in 15 minutes.', ['180g prawns', '120g cannellini beans', '2 cloves garlic', '1 tsp paprika', '1 tbsp olive oil', '80g spinach']),
  d('lunch', 'Chicken shawarma bowl', MIDE, 'Toss the chicken in cumin and paprika, roast until charred, and serve over the bulgur with cucumber, tomato and a tahini and lemon drizzle.', ['170g chicken breast', '100g bulgur wheat cooked', '100g cucumber', '100g tomato', '1 tbsp tahini', '1 tsp cumin', '1 tsp paprika', '20g lemon']),
  d('lunch', 'Blackened chicken and rice', CAJU, 'Coat the chicken in cajun seasoning, sear until blackened at the edges, and serve over rice with softened peppers, onion and okra.', ['170g chicken breast', '1 tsp cajun seasoning', '100g white rice cooked', '100g bell pepper', '60g onion', '60g okra']),
  d('lunch', 'Dill salmon and potato salad', NORD, 'Bake the salmon and flake it over warm potatoes, cucumber and green beans dressed with yoghurt and dill.', ['150g salmon', '120g potato boiled', '100g cucumber', '60g greek yoghurt 0%', '1 tsp dill', '100g green beans']),
  d('lunch', 'Quorn pesto pasta', ITAL, 'Brown the quorn mince, toss with the pasta, pesto and cherry tomatoes, and stir through the spinach until wilted.', ['240g quorn mince', '100g wholewheat pasta cooked', '1 tbsp pesto', '100g cherry tomatoes', '60g spinach']),
  d('lunch', 'Halloumi and chicken quinoa salad', MEDI, 'Grill the halloumi until golden and toss with the quinoa, cucumber, tomatoes and rocket, then top with halved boiled eggs.', ['70g halloumi', '100g chicken breast', '60g quinoa cooked', '100g cucumber', '100g cherry tomatoes', '60g rocket']),
  d('lunch', 'Tofu bibimbap', KORE, 'Pan-fry the tofu, then arrange over the rice with the spinach, carrot and sprouts, top with a fried egg and stir through gochujang and sesame oil.', ['220g tofu firm', '100g brown rice cooked', '60g spinach', '60g carrot', '40g bean sprouts', '1 egg', '1 tbsp gochujang', '1 tsp sesame oil']),
  d('lunch', 'Baked chicken katsu bowl', JAPA, 'Coat the chicken in egg and breadcrumbs, bake until crisp and cooked through, slice and serve over rice with shredded cabbage.', ['170g chicken breast', '1 egg', '20g breadcrumbs', '100g white rice cooked', '100g cabbage']),
  d('lunch', 'Turkey larb lettuce cups with rice', THAI, 'Fry the turkey with the onion and chilli, then toss with fish sauce and lime and spoon into the salad leaves, with a little rice on the side.', ['170g turkey mince', '60g mixed salad leaves', '1 tbsp fish sauce', '20g lime', '40g onion', '100g white rice cooked', '1 tsp chili powder']),
  d('lunch', 'Chicken, leek and mash', BRIT, 'Gently cook the leeks in butter, add the chicken and peas and simmer until tender, and serve over the mash.', ['170g chicken breast', '130g mashed potato', '100g leek', '100g peas', '1 tsp butter']),
  d('lunch', 'Smoked salmon and quark toast', AMER, 'Toast the bread, spread with quark, and layer with smoked salmon and cucumber. Ready in 5 minutes.', ['90g wholemeal bread', '100g smoked salmon', '100g quark', '60g cucumber']),
  d('lunch', 'Tuna jacket potato', BRIT, 'Bake the potato until soft, split and fill with tuna stirred through yoghurt and sweetcorn, and serve with salad.', ['150g tuna canned in water', '200g potato baked', '60g sweetcorn', '60g greek yoghurt 0%', '60g mixed salad leaves']),
  d('lunch', 'Beef and vegetable noodle stir-fry', KORE, 'Stir-fry the beef strips, add the carrot, mushroom and spinach, then toss with the noodles, soy sauce and sesame oil.', ['160g beef steak sirloin', '100g egg noodles cooked', '100g spinach', '60g carrot', '60g mushroom', '1 tbsp soy sauce', '1 tsp sesame oil']),
  d('lunch', 'Chicken and avocado quinoa bowl', AMER, 'Slice the grilled chicken over the quinoa, leaves and tomatoes, add sliced avocado and dress with balsamic vinegar.', ['170g chicken breast', '50g avocado', '80g mixed salad leaves', '100g cherry tomatoes', '100g quinoa cooked', '1 tbsp balsamic vinegar']),
  d('lunch', 'Tempeh teriyaki rice bowl', JAPA, 'Fry the tempeh until golden, glaze with teriyaki sauce, and serve over the rice with steamed broccoli and carrot.', ['180g tempeh', '90g white rice cooked', '100g broccoli', '1 tbsp teriyaki sauce', '1 tsp sesame oil', '60g carrot']),
  d('lunch', 'Soy mince burrito bowl', MEXI, 'Fry the soy mince with cumin until browned, and build a bowl with the rice, warm beans, sweetcorn, salsa and avocado.', ['120g soy mince', '100g brown rice cooked', '80g black beans', '80g salsa', '40g avocado', '60g sweetcorn', '1 tsp cumin']),
  d('lunch', 'Seitan gyro plate', MEDI, 'Pan-fry the seitan with paprika until crisp at the edges, and serve in a warm pitta with cucumber, tomato and soy yoghurt.', ['170g seitan strips', '1 pitta bread', '100g cucumber', '100g tomato', '60g soy yoghurt', '1 tsp paprika']),
  d('lunch', 'Peanut tofu noodle bowl', THAI, 'Fry the tofu until golden, toss with the noodles, carrot and sprouts in a dressing of peanut butter, soy sauce and lime.', ['200g tofu firm', '100g rice noodles cooked', '1 tbsp peanut butter', '60g carrot', '60g bean sprouts', '1 tbsp soy sauce', '20g lime']),
  d('lunch', 'Edamame and tofu quinoa power bowl', JAPA, 'Toss the warm quinoa with the edamame, cubed tofu and cucumber, and dress with tamari and sesame seeds.', ['150g edamame', '100g quinoa cooked', '100g tofu firm', '60g cucumber', '1 tbsp tamari', '1 tsp sesame seeds']),
  d('lunch', 'Egg fried rice with tofu', JAPA, 'Fry the tofu until golden, scramble in the eggs, then toss with the rice, peas and carrot and season with soy sauce.', ['2 egg', '150g tofu firm', '100g white rice cooked', '60g peas', '60g carrot', '1 tbsp soy sauce']),
  d('lunch', 'Ricotta and spinach protein pasta', ITAL, 'Toss the hot pasta with the ricotta, wilted spinach, tomatoes and parmesan until creamy.', ['120g ricotta cheese', '100g protein pasta', '80g spinach', '100g cherry tomatoes', '20g parmesan']),
  d('lunch', 'Paneer bhurji wrap', INDI, 'Scramble the paneer with the eggs, garam masala and spinach, and roll up in a warm tortilla.', ['70g paneer', '2 egg', '120g egg white', '50g tortilla wrap', '60g spinach', '1 tsp garam masala']),
  d('lunch', 'Seitan and edamame rice bowl', JAPA, 'Sear the seitan in soy sauce and serve over the rice with steamed broccoli and edamame.', ['170g seitan strips', '80g white rice cooked', '100g edamame', '100g broccoli', '1 tbsp soy sauce']),
  d('lunch', 'Tofu and chickpea salad with tahini', MIDE, 'Bake the tofu until golden and toss with the chickpeas, cucumber and tomatoes in a dressing of tahini, lemon and a splash of water.', ['200g tofu firm', '80g chickpeas', '100g cucumber', '100g cherry tomatoes', '1 tbsp tahini', '20g lemon']),
  d('lunch', 'Soy mince taco salad', MEXI, 'Fry the soy mince with spices until crisp, and pile onto salad leaves with beans, salsa and guacamole.', ['140g soy mince', '80g mixed salad leaves', '80g black beans', '80g salsa', '30g guacamole']),
  d('lunch', 'Tempeh Caesar-style salad', AMER, 'Crisp the tempeh in a hot pan and toss with the leaves and tomatoes in olive oil, lemon and nutritional yeast.', ['180g tempeh', '100g mixed salad leaves', '100g cherry tomatoes', '1 tbsp olive oil', '1 tbsp nutritional yeast', '20g lemon']),
  d('lunch', 'Seitan kebab wrap', MIDE, 'Sear the seasoned seitan until charred, and roll into a warm tortilla with cucumber, tomato and hummus.', ['160g seitan strips', '60g tortilla wrap', '100g cucumber', '60g tomato', '40g hummus']),
]
const DINNERS: RawProposal[] = [
  d('dinner', 'Baked salmon with greens and new potatoes', BRIT, 'Roast the salmon with a squeeze of lemon until just cooked, and serve with boiled potatoes and steamed broccoli and green beans.', ['170g salmon', '100g potato boiled', '100g broccoli', '100g green beans', '20g lemon', '1 tsp olive oil']),
  d('dinner', 'Chicken tikka with spinach and basmati rice', INDI, 'Marinate the chicken in yoghurt and curry paste, grill until charred and serve over the rice with garlicky spinach.', ['180g chicken breast', '80g natural yoghurt', '1 tbsp curry paste', '120g basmati rice cooked', '100g spinach']),
  d('dinner', 'Beef chilli with rice', AMER, 'Brown the beef with the onion and peppers, add the spices, beans and tomatoes and simmer until thick, and serve over the rice.', ['160g beef mince 5% fat', '100g kidney beans', '200g chopped tomatoes canned', '100g white rice cooked', '60g bell pepper', '40g onion', '1 tsp chili powder', '1 tsp cumin']),
  d('dinner', 'Lemon herb cod with potatoes and green beans', BRIT, 'Bake the cod with lemon and dill until flaking, and serve with boiled potatoes and green beans dressed in a little olive oil.', ['190g cod', '150g potato boiled', '120g green beans', '20g lemon', '1 tsp dill', '1 tsp olive oil']),
  d('dinner', 'Turkey bolognese with wholewheat spaghetti', ITAL, 'Brown the turkey with the onion and mushrooms, add the passata and simmer until rich, then serve over the pasta with grated parmesan.', ['170g turkey mince', '200g tomato passata', '120g wholewheat pasta cooked', '60g mushroom', '40g onion', '20g parmesan']),
  d('dinner', 'Teriyaki chicken stir-fry with noodles', JAPA, 'Stir-fry the chicken until golden, add the broccoli and pepper, then toss with the noodles and teriyaki sauce.', ['180g chicken breast', '100g egg noodles cooked', '100g broccoli', '60g bell pepper', '2 tbsp teriyaki sauce']),
  d('dinner', 'Thai green chicken curry', THAI, 'Fry the curry paste, add the chicken and coconut milk with the beans and bamboo shoots and simmer until cooked, and serve with rice.', ['180g chicken breast', '60g coconut milk canned', '1 tbsp curry paste', '80g green beans', '60g bamboo shoots', '120g basmati rice cooked']),
  d('dinner', 'Steak with roasted vegetables and potato', BRIT, 'Sear the steak to taste and rest it, and serve with a baked potato and roasted asparagus and mushrooms.', ['180g beef steak sirloin', '150g potato baked', '100g asparagus', '80g mushroom', '1 tsp olive oil']),
  d('dinner', 'Garlic prawn linguine', ITAL, 'Soften the garlic in olive oil, add the tomatoes and prawns, and toss with the pasta and wilted spinach.', ['190g prawns', '110g pasta cooked', '200g chopped tomatoes canned', '2 cloves garlic', '60g spinach', '1 tsp olive oil']),
  d('dinner', 'Lamb kofta with tzatziki and couscous', MIDE, 'Mix the lamb with cumin and paprika, shape into koftas and grill, and serve with couscous, cucumber and tzatziki.', ['160g lamb mince', '1 tsp cumin', '1 tsp paprika', '100g couscous cooked', '100g cucumber', '60g tzatziki']),
  d('dinner', 'Bulgogi-style beef with rice and spinach', KORE, 'Marinate the beef in soy sauce, sesame oil and gochujang, sear quickly and serve over rice with wilted spinach and carrot.', ['180g beef steak sirloin', '100g white rice cooked', '100g spinach', '1 tbsp soy sauce', '1 tsp sesame oil', '1 tbsp gochujang', '60g carrot']),
  d('dinner', 'Beef noodle soup', VIET, 'Simmer the broth with star anise, add the noodles, bok choy and sprouts, and top with thin slices of quickly seared steak.', ['160g beef steak sirloin', '100g rice noodles cooked', '300ml beef broth', '60g bean sprouts', '80g bok choy', '1 star anise']),
  d('dinner', 'Jerk chicken thighs with rice and peas', CARI, 'Coat the chicken in jerk paste, roast until charred and cooked through, and serve over rice stirred with kidney beans, with sliced pepper.', ['200g chicken thigh', '1 tbsp jerk seasoning paste', '110g white rice cooked', '70g kidney beans', '60g bell pepper']),
  d('dinner', 'Chicken fajitas', MEXI, 'Sear the spiced chicken strips with the peppers and onion, then fill the warm tortillas and top with guacamole and salsa.', ['170g chicken breast', '70g tortilla wrap', '100g bell pepper', '60g onion', '40g guacamole', '50g salsa', '1 tsp chili powder', '1 tsp cumin']),
  d('dinner', 'Turkey shepherd\'s pie with mash', BRIT, 'Brown the turkey with carrot and peas in passata, spoon into a dish, top with mashed potato and bake until golden.', ['170g turkey mince', '150g mashed potato', '80g peas', '60g carrot', '100g tomato passata']),
  d('dinner', 'Baked haddock with lentils', BRIT, 'Bake the haddock until flaking, and serve on a bed of lentils stirred through with spinach and a little olive oil.', ['190g haddock', '120g lentils green', '80g spinach', '1 tsp olive oil', '20g lemon']),
  d('dinner', 'Mackerel with beetroot and potatoes', NORD, 'Grill the mackerel until the skin crisps, and serve with boiled potatoes, beetroot and a dill yoghurt.', ['150g mackerel', '120g potato boiled', '80g beetroot', '100g greek yoghurt 0%', '1 tsp dill']),
  d('dinner', 'Seared tuna with quinoa and green beans', MEDI, 'Sear the tuna steak briefly on each side, and serve sliced over the quinoa with green beans, olives and a squeeze of lemon.', ['180g tuna steak fresh', '110g quinoa cooked', '120g green beans', '20g olives', '20g lemon', '1 tsp olive oil']),
  d('dinner', 'Lemon chicken with asparagus and pasta', ITAL, 'Pan-fry the chicken and set aside, then toss the pasta and asparagus in a sauce of lemon, capers and a little butter and serve the chicken on top.', ['180g chicken breast', '110g pasta cooked', '100g asparagus', '20g lemon', '1 tbsp capers', '1 tsp butter']),
  d('dinner', 'Turkey stroganoff with noodles', BRIT, 'Brown the turkey strips with the mushrooms and paprika, stir in the sour cream off the heat and serve over the noodles.', ['170g turkey breast', '120g mushroom', '40g sour cream', '110g egg noodles cooked', '1 tsp paprika']),
  d('dinner', 'Tofu and broccoli stir-fry', JAPA, 'Fry the tofu until golden, add the broccoli and carrot, and toss through the soy sauce and sesame oil, and serve over the rice.', ['220g tofu firm', '100g brown rice cooked', '100g broccoli', '60g carrot', '1 tbsp soy sauce', '1 tsp sesame oil']),
  d('dinner', 'Tempeh tacos', MEXI, 'Crumble and fry the tempeh with the spices, and pile into warm corn tortillas with shredded cabbage, guacamole and salsa.', ['170g tempeh', '2 corn tortilla', '60g cabbage', '40g guacamole', '60g salsa', '1 tsp cumin', '1 tsp chili powder']),
  d('dinner', 'Red lentil and tofu dal with rice', INDI, 'Simmer the lentils with the curry paste until soft, stir in the spinach, and serve over the rice with pan-fried tofu on top.', ['100g lentils red', '150g tofu firm', '1 tbsp curry paste', '80g spinach', '100g basmati rice cooked', '100g chopped tomatoes canned']),
  d('dinner', 'Seitan and pepper skewers with couscous', MIDE, 'Thread the seitan and peppers on skewers with cumin, grill until charred, and serve over the couscous with cucumber.', ['180g seitan strips', '100g bell pepper', '100g couscous cooked', '100g cucumber', '1 tsp cumin', '1 tsp olive oil']),
  d('dinner', 'Quorn cottage pie', BRIT, 'Brown the quorn with carrot and peas in passata, spoon into a dish, top with mash and bake until golden.', ['200g quorn mince', '120g mashed potato', '80g peas', '60g carrot', '100g tomato passata']),
  d('dinner', 'Chicken and prawn paella-style rice', SPAN, 'Fry the chicken and chorizo, add the rice, peppers and peas with the paprika, and finish with the prawns until just pink.', ['130g chicken breast', '80g prawns', '20g chorizo', '110g white rice cooked', '60g peas', '80g bell pepper', '1 tsp paprika']),
  d('dinner', 'Fish and coconut stew with rice', BRAZ, 'Simmer the peppers and tomatoes in coconut milk, add the fish and cook until flaking, and serve over rice.', ['180g tilapia', '60g coconut milk canned', '80g bell pepper', '100g chopped tomatoes canned', '110g white rice cooked']),
  d('dinner', 'Spiced chicken with egg and injera', ETHI, 'Simmer the chicken in berbere and onion until tender, add a boiled egg, and serve with torn injera.', ['180g chicken thigh', '1 egg', '1 tsp berbere spice mix', '60g onion', '60g injera flatbread', '80g cabbage']),
  d('dinner', 'Peanut chicken stew', WAFR, 'Simmer the chicken in tomatoes with the peanut butter until the sauce thickens, stir in the spinach, and serve with sweet potato.', ['180g chicken breast', '1 tbsp peanut butter', '200g chopped tomatoes canned', '120g sweet potato baked', '60g spinach']),
  d('dinner', 'Beef and potato stir-fry', PERU, 'Sear the beef strips with the onion and tomato in soy sauce, toss through the roasted potato, and serve with a little rice.', ['170g beef steak sirloin', '120g potato baked', '60g onion', '80g tomato', '1 tbsp soy sauce', '80g white rice cooked']),
  d('dinner', 'Kidney bean and cheese stew', GEOR, 'Simmer the beans with onion, walnuts and coriander until thick, and stir in the cheese at the end.', ['150g kidney beans', '50g sulguni cheese', '20g walnuts', '60g onion', '1 tsp coriander', '150g tofu firm']),
  d('dinner', 'Cajun prawns with polenta', CAJU, 'Toss the prawns in cajun seasoning and sear with the peppers, and serve over creamy polenta.', ['190g prawns', '1 tsp cajun seasoning', '130g polenta cooked', '100g bell pepper', '60g okra']),
  d('dinner', 'Turkey meatballs with mash and peas', NORD, 'Mix the turkey with egg and breadcrumbs, roll and bake, then serve with mash, peas and a light yoghurt sauce.', ['170g turkey mince', '1 egg', '15g breadcrumbs', '130g mashed potato', '80g peas', '60g greek yoghurt 0%']),
  d('dinner', 'Chicken souvlaki plate', MEDI, 'Grill the marinated chicken skewers and serve with tzatziki, cucumber, tomato and a little rice.', ['180g chicken breast', '60g tzatziki', '100g cucumber', '100g tomato', '100g white rice cooked', '1 tsp olive oil']),
  d('dinner', 'Light chicken parmigiana with pasta', ITAL, 'Bake the chicken under passata and mozzarella until bubbling, finish with parmesan, and serve with pasta.', ['170g chicken breast', '150g tomato passata', '40g mozzarella', '15g parmesan', '110g wholewheat pasta cooked']),
  d('dinner', 'Pesto chicken with courgette and pasta', ITAL, 'Pan-fry the chicken, then toss the courgette, tomatoes and pasta with the pesto and serve the chicken on top.', ['170g chicken breast', '1 tbsp pesto', '200g courgette', '100g cherry tomatoes', '100g pasta cooked']),
  d('dinner', 'Smoked paprika pork with potatoes and beans', SPAN, 'Rub the pork with paprika and roast until cooked through, and serve sliced with roasted potatoes and green beans.', ['180g pork loin', '1 tsp paprika', '130g potato baked', '120g green beans', '1 tsp olive oil']),
  d('dinner', 'Baked cod with chorizo and butter beans', SPAN, 'Bake the cod over the beans, chorizo and tomatoes until the fish flakes, and finish with wilted spinach.', ['180g cod', '20g chorizo', '130g butter beans', '100g chopped tomatoes canned', '60g spinach']),
  d('dinner', 'Salmon poke-style bowl', JAPA, 'Flake the baked salmon over the rice with edamame, cucumber and avocado and dress with soy sauce and sesame oil.', ['140g salmon', '60g white rice cooked', '150g edamame', '70g cucumber', '1 tbsp soy sauce', '1 tsp sesame oil']),
  d('dinner', 'Chicken saag with basmati rice', INDI, 'Simmer the chicken in spices and tomatoes, stir in the spinach until wilted, and serve with the rice and a spoon of yoghurt.', ['180g chicken breast', '150g spinach', '100g chopped tomatoes canned', '1 tsp garam masala', '100g basmati rice cooked', '60g natural yoghurt']),
  d('dinner', 'Paneer and tofu tikka with rice', INDI, 'Marinate the paneer and tofu in yoghurt and garam masala, grill until golden, and serve over the rice with peppers.', ['80g paneer', '150g tofu firm', '60g natural yoghurt', '1 tsp garam masala', '100g basmati rice cooked', '80g bell pepper']),
  d('dinner', 'Turkey burger bowl with sweet potato', AMER, 'Shape the turkey into a patty and grill until cooked through, and serve over salad leaves with roasted sweet potato, tomato and mustard.', ['180g turkey mince', '130g sweet potato baked', '80g mixed salad leaves', '60g tomato', '1 tbsp mustard']),
  d('dinner', 'Barbecue chicken with corn and slaw', AMER, 'Brush the chicken with barbecue sauce and grill until sticky, and serve with sweetcorn, coleslaw and a baked potato.', ['180g chicken breast', '1 tbsp bbq sauce', '100g sweetcorn', '60g coleslaw', '120g potato baked']),
  d('dinner', 'Pork loin with apple and cabbage', BRIT, 'Roast the pork until cooked through and serve with softened cabbage, apple slices and boiled potatoes.', ['180g pork loin', '100g cabbage', '80g apple', '130g potato boiled', '1 tsp mustard']),
  d('dinner', 'Mussels in tomato and garlic with pasta', ITAL, 'Steam the mussels in a sauce of tomatoes and garlic until they open, and toss through the pasta.', ['220g mussels', '100g pasta cooked', '200g chopped tomatoes canned', '2 cloves garlic', '1 tsp olive oil']),
  d('dinner', 'Sea bass with fennel and couscous', MEDI, 'Roast the sea bass on sliced fennel with lemon until the flesh flakes, and serve with couscous.', ['190g sea bass', '100g fennel', '100g couscous cooked', '20g lemon', '1 tsp olive oil']),
  d('dinner', 'Chicken and white bean soup', BRIT, 'Simmer the chicken, carrot and celery in the broth, add the beans and greens, and shred the chicken back in before serving.', ['170g chicken breast', '300ml chicken broth', '120g cannellini beans', '60g carrot', '40g celery', '60g kale']),
  d('dinner', 'Egg and spinach curry with rice', INDI, 'Simmer the tomatoes with the curry paste, add the spinach, nestle in halved boiled eggs and serve over the rice.', ['3 egg', '120g spinach', '150g chopped tomatoes canned', '1 tbsp curry paste', '100g basmati rice cooked', '100g tofu firm']),
  d('dinner', 'Honey soy salmon with rice and bok choy', JAPA, 'Glaze the salmon with soy sauce and a little honey, bake until cooked, and serve over rice with steamed bok choy.', ['150g salmon', '80g white rice cooked', '120g bok choy', '1 tbsp soy sauce', '1 tsp honey', '80g edamame']),
  d('dinner', 'Spiced lamb with chickpeas and yoghurt', MIDE, 'Brown the lamb with cumin and paprika, stir in the chickpeas and tomatoes, and serve with a cool yoghurt dressing.', ['150g lamb mince', '100g chickpeas', '100g chopped tomatoes canned', '1 tsp cumin', '1 tsp paprika', '100g greek yoghurt 0%']),
  d('dinner', 'Vegan mince and bean casserole', BRIT, 'Brown the vegan mince with the onion, add the beans and tomatoes and simmer until thick, and serve with kale.', ['180g vegan mince', '80g cannellini beans', '200g chopped tomatoes canned', '60g onion', '60g kale']),
  d('dinner', 'Vegan bolognese with wholewheat spaghetti', ITAL, 'Brown the vegan mince with the onion and mushrooms, add the passata and simmer until rich, and serve over the pasta.', ['150g vegan mince', '200g tomato passata', '110g wholewheat pasta cooked', '60g mushroom', '40g onion']),
  d('dinner', 'Coconut chickpea and tofu curry', INDI, 'Fry the curry paste, add the chickpeas and coconut milk and simmer, then stir in the spinach and pan-fried tofu, and serve with the rice.', ['200g tofu firm', '60g chickpeas', '30g coconut milk canned', '1 tbsp curry paste', '80g spinach', '80g basmati rice cooked']),
  d('dinner', 'Tempeh stir-fry with noodles', KORE, 'Fry the tempeh until crisp, add the bok choy and mushrooms, and toss with the noodles, soy sauce and gochujang.', ['180g tempeh', '100g rice noodles cooked', '100g bok choy', '60g mushroom', '1 tbsp soy sauce', '1 tbsp gochujang']),
  d('dinner', 'Jerk tofu with rice and peas', CARI, 'Coat the pressed tofu in jerk paste and bake until charred, and serve over rice stirred with kidney beans, with sliced pepper.', ['220g tofu firm', '1 tbsp jerk seasoning paste', '100g white rice cooked', '70g kidney beans', '60g bell pepper']),
  d('dinner', 'Seitan fajita bowl', MEXI, 'Sear the seitan with the peppers, onion and cumin, and serve over the rice with guacamole.', ['180g seitan strips', '100g bell pepper', '60g onion', '100g brown rice cooked', '50g guacamole', '1 tsp cumin']),
  d('dinner', 'Protein pasta arrabbiata with mozzarella', ITAL, 'Simmer the passata with the chilli, toss through the pasta and spinach, and melt over the mozzarella.', ['100g protein pasta', '200g tomato passata', '60g mozzarella', '60g spinach', '1 tsp chili powder']),
  d('dinner', 'Soy mince chilli with rice', AMER, 'Brown the soy mince with the onion and spices, add the beans and tomatoes and simmer until thick, and serve over rice.', ['120g soy mince', '120g kidney beans', '200g chopped tomatoes canned', '100g white rice cooked', '60g bell pepper', '1 tsp chili powder', '1 tsp cumin']),
  d('dinner', 'Seitan stir-fry with noodles', KORE, 'Sear the seitan, add the bok choy and carrot, and toss with the noodles, soy sauce and gochujang.', ['180g seitan strips', '100g rice noodles cooked', '100g bok choy', '60g carrot', '1 tbsp soy sauce', '1 tbsp gochujang']),
  d('dinner', 'Miso tofu with rice and greens', JAPA, 'Brush the tofu with miso and bake until caramelised, and serve over the rice with steamed bok choy and edamame.', ['220g tofu firm', '1 tbsp miso paste', '90g white rice cooked', '120g bok choy', '80g edamame']),
  d('dinner', 'Tempeh and sweet potato bowl', AMER, 'Roast the tempeh with paprika until crisp, and serve with baked sweet potato and garlicky kale, drizzled with tahini.', ['180g tempeh', '120g sweet potato baked', '100g kale', '1 tbsp tahini', '1 tsp paprika']),
  d('dinner', 'Vegan mince shepherd\'s pie', BRIT, 'Brown the vegan mince with carrot and peas in passata, spoon into a dish, top with mashed potato and bake until golden.', ['170g vegan mince', '150g potato boiled', '80g peas', '60g carrot', '100g tomato passata']),
  d('dinner', 'Tofu laksa-style noodle soup', THAI, 'Simmer the curry paste with coconut milk and water, add the bok choy, noodles and pan-fried tofu, and heat through.', ['200g tofu firm', '100g rice noodles cooked', '30g coconut milk canned', '1 tbsp curry paste', '100g bok choy', '200ml water']),
]
const SNACKS: RawProposal[] = [
  d('snack', 'Skyr with berries and honey', BRIT, 'Spoon the skyr into a bowl, top with the berries and a drizzle of honey. Ready in 2 minutes.', ['220g skyr', '80g mixed berries', '1 tsp honey']),
  d('snack', 'Cottage cheese and pineapple', BRIT, 'Spoon the cottage cheese into a bowl and top with the pineapple. Ready in 2 minutes.', ['180g cottage cheese', '90g pineapple']),
  d('snack', 'Banana protein shake', AMER, 'Blend the protein powder, milk and banana until smooth. Ready in 2 minutes.', ['30g whey protein powder', '250ml milk semi skimmed', '80g banana']),
  d('snack', 'Greek yoghurt with walnuts and honey', MEDI, 'Spoon the yoghurt into a bowl and top with crushed walnuts and a drizzle of honey. Ready in 2 minutes.', ['220g greek yoghurt 0%', '12g walnuts', '1 tsp honey']),
  d('snack', 'Tuna on rice cakes', BRIT, 'Mix the tuna with a little yoghurt and pile onto the rice cakes with sliced cucumber. Ready in 5 minutes.', ['90g tuna canned in water', '2 rice cakes', '50g cucumber', '30g greek yoghurt 0%']),
  d('snack', 'Boiled egg with cottage cheese and tomatoes', BRIT, 'Boil the egg to your liking, then halve and serve with the cottage cheese and tomatoes. Ready in 10 minutes.', ['1 egg', '150g cottage cheese', '80g cherry tomatoes']),
  d('snack', 'Turkey and cucumber roll-ups', MEDI, 'Spread the turkey slices with hummus, roll around the cucumber sticks and serve. Ready in 5 minutes.', ['110g turkey breast', '60g cucumber', '25g hummus']),
  d('snack', 'Steamed edamame with sesame', JAPA, 'Steam the edamame until tender and toss with a little sesame oil. Ready in 5 minutes.', ['200g edamame', '1 tsp sesame oil']),
  d('snack', 'Quark with mango', INDI, 'Spoon the quark into a bowl and top with the mango and a pinch of cinnamon. Ready in 2 minutes.', ['220g quark', '70g mango', '1 tsp cinnamon']),
  d('snack', 'Apple with peanut butter and skyr', AMER, 'Slice the apple and serve with the peanut butter and a bowl of skyr. Ready in 3 minutes.', ['150g apple', '1 tbsp peanut butter', '150g skyr']),
  d('snack', 'Beef jerky and skyr pot with orange', AMER, 'Eat the jerky with the skyr and orange segments. Ready in 2 minutes.', ['50g beef jerky', '100g skyr', '80g orange']),
  d('snack', 'Chocolate yoghurt pot', AMER, 'Stir the protein powder through the yoghurt, top with the raspberries and grated dark chocolate. Ready in 3 minutes.', ['200g greek yoghurt 0%', '30g whey protein powder', '10g dark chocolate', '80g raspberries']),
  d('snack', 'Ricotta and strawberry toast', ITAL, 'Toast the bread, spread with ricotta and top with sliced strawberries and a drizzle of honey. Ready in 5 minutes.', ['50g wholemeal bread', '80g ricotta cheese', '60g strawberries', '100g skyr']),
  d('snack', 'Smoked salmon and cucumber bites', NORD, 'Spread the cucumber rounds with quark and top with strips of smoked salmon. Ready in 5 minutes.', ['70g smoked salmon', '100g cucumber', '80g quark']),
  d('snack', 'Soy yoghurt with chia and berries', BRIT, 'Stir the chia seeds and protein powder through the soy yoghurt, top with blueberries and chill briefly.', ['200g soy yoghurt', '1 tbsp chia seeds', '30g vegan protein powder', '80g blueberries']),
  d('snack', 'Vegan banana protein shake', BRIT, 'Blend the protein powder, soy milk and banana until smooth. Ready in 2 minutes.', ['30g vegan protein powder', '250ml soy milk', '80g banana']),
  d('snack', 'Sardines on crispbread', NORD, 'Mash the sardines with lemon and spread onto the crispbread. Ready in 5 minutes.', ['90g sardines canned', '2 rye crispbread', '20g lemon']),
  d('snack', 'Cottage cheese and cucumber dip with crackers', MEDI, 'Stir the cucumber through the cottage cheese and serve with the crackers. Ready in 5 minutes.', ['170g cottage cheese', '60g cucumber', '20g crackers']),
  d('snack', 'Prawn and avocado cups', PERU, 'Spoon the cooked prawns into lettuce cups with avocado and cherry tomatoes. Ready in 5 minutes.', ['100g prawns', '30g avocado', '50g cherry tomatoes', '40g mixed salad leaves']),
  d('snack', 'Spinach and feta egg white bites', MEDI, 'Whisk the egg whites with the spinach and feta, pour into a muffin tin and bake until set.', ['150g egg white', '40g spinach', '20g feta cheese']),
  d('snack', 'Raspberry protein overnight oats pot', BRIT, 'Stir the oats, yoghurt and raspberries together in a pot and chill overnight.', ['30g oats', '180g greek yoghurt 0%', '60g raspberries']),
  d('snack', 'Chicken and avocado lettuce wraps', MEXI, 'Spoon sliced cooked chicken and avocado into the salad leaves and fold. Ready in 5 minutes.', ['100g chicken breast', '30g avocado', '40g mixed salad leaves']),
  d('snack', 'Pistachio skyr pot', MEDI, 'Spoon the skyr into a pot, top with crushed pistachios and a few chopped dates. Ready in 3 minutes.', ['220g skyr', '10g pistachios', '15g dates']),
  d('snack', 'Tofu and edamame bowl', JAPA, 'Cube the silken tofu and serve with the steamed edamame, a splash of soy sauce and sesame seeds.', ['150g tofu silken', '120g edamame', '1 tsp soy sauce', '1 tsp sesame seeds']),
  d('snack', 'Vegan berry protein shake', BRIT, 'Blend the protein powder, soy milk and berries until smooth. Ready in 2 minutes.', ['30g vegan protein powder', '250ml soy milk', '80g mixed berries']),
  d('snack', 'Edamame and almond pot', JAPA, 'Steam the edamame and serve with a few crushed almonds. Ready in 5 minutes.', ['200g edamame', '10g almonds']),
  d('snack', 'Silken tofu chocolate pudding', AMER, 'Blend the silken tofu with the protein powder and melted chocolate until smooth and chill. Ready in 5 minutes.', ['200g tofu silken', '30g vegan protein powder', '10g dark chocolate']),
  d('snack', 'Seitan bites with hummus', MIDE, 'Pan-fry the seitan pieces until crisp and serve with hummus and cucumber sticks. Ready in 10 minutes.', ['100g seitan strips', '30g hummus', '80g cucumber']),
]

/** Every dish in the library. The order is authoring order; choosing is the chooser's job. */
export const MEAL_LIBRARY: readonly RawProposal[] = [...BREAKFASTS, ...LUNCHES, ...DINNERS, ...SNACKS]
