// ---------------------------------------------------------------------------
// Pure derivations shared by useActiveSession and (from P2 onward) the
// today-first session UI. Nothing here reads localStorage or Supabase — every
// function takes its inputs explicitly so it can be unit-tested without a
// store and reused identically by the hook and by test:session-derive.
//
// LAYOUT-DESIGN.md §5.2 designates `setsFor` as the SOLE source for
// checkmarks, counts, isComplete, progress, and off-plan detection — no
// component may filter `logs` itself. This file is where that filter lives.
// ---------------------------------------------------------------------------

import { getExerciseEntry } from './exercise-db'
import { anchorDifficultyBump } from './movement-difficulty'
import { isMalformedZeroWeight } from './set-log-store'
import { loadingMode, roundToPlate, getEquipmentFloorKg, isUnverifiedLoadSource } from './load-prescription'
import type { Exercise, ExerciseSetLog, WorkoutDay } from './types'
import type { WarmupItem } from './warmup'

/**
 * The rows that count as "this exercise's logged sets" for every derived
 * fact on the session view. Matches on `exercise_id` when the row has one
 * (every row written through set-log-store does); falls back to name only
 * for pre-C0 legacy rows. Excludes warm-up rows (ramp ticks are UI-only and
 * never written here, but a dev-seeded or chat-logged warmup row must not
 * inflate a completion count) and malformed zero-weight rows (a save that
 * failed validation but slipped through before the guard existed).
 */
export function filterLoggableSets(
  logs: ExerciseSetLog[],
  exerciseId: string,
  exerciseName?: string,
): ExerciseSetLog[] {
  return logs.filter(l => {
    const matches = l.exercise_id ? l.exercise_id === exerciseId : l.exercise_name === exerciseName
    if (!matches) return false
    if (l.is_warmup) return false
    if (isMalformedZeroWeight(l)) return false
    return true
  })
}

// ---------------------------------------------------------------------------
// Warm-up shape normalization (cleanup round, defect 1) — a profile whose
// mesocycle_weeks row predates a WarmupBlock field addition (e.g. `ramp_ups`,
// added by the ramp-up-visibility fix) still has that JSON sitting in the
// live DB exactly as it was written; nothing rewrites it on read. Both
// WarmupSection.tsx and its legacy twin in ExercisePlan.tsx used to assume
// `general`/`mobility` were always arrays and `total_seconds` always a
// number — true for anything generated by the current buildWarmup, false for
// older or hand-edited rows. Centralized here so both call sites degrade
// identically instead of drifting.
// ---------------------------------------------------------------------------

export interface NormalizedWarmup {
  general: WarmupItem[]
  mobility: WarmupItem[]
  /** Count of ramped compounds (buildWarmup's ramp_ups, one per qualifying heavy lift) — their set time is already folded into totalMinutes via rampSeconds, so the displayed move count must include them too or the chip undercounts what it's timing. */
  rampCount: number
  totalMinutes: number
  coachNote?: string
}

/** Returns null when there is genuinely nothing renderable — callers should render nothing, exactly like the old `!warmup` guard. */
export function normalizeWarmup(warmup: WorkoutDay['warmup'] | null | undefined): NormalizedWarmup | null {
  if (!warmup || typeof warmup !== 'object') return null
  const general = Array.isArray(warmup.general) ? warmup.general : []
  const mobility = Array.isArray(warmup.mobility) ? warmup.mobility : []
  const rampCount = Array.isArray(warmup.ramp_ups) ? warmup.ramp_ups.length : 0
  const coachNote = typeof warmup.coach_note === 'string' && warmup.coach_note.length > 0 ? warmup.coach_note : undefined
  if (general.length === 0 && mobility.length === 0 && rampCount === 0 && !coachNote) return null
  const totalSeconds = typeof warmup.total_seconds === 'number' && Number.isFinite(warmup.total_seconds) ? warmup.total_seconds : 0
  return { general, mobility, rampCount, totalMinutes: Math.round(totalSeconds / 60), coachNote }
}

// ---------------------------------------------------------------------------
// Ramp display (LAYOUT-DESIGN.md §1.5/§1.6/§7.5) — moved from ExercisePlan.tsx
// so both the legacy stand-in and the new SetGrid/RampStrip can share the
// exact same logic. Three shapes now instead of one nullable array: the
// original kg list, a rep-only variant for bodyweight compounds (the
// percentage block this replaces used to be the only surface for these —
// deleting it without this branch would silently drop the ramp), and a
// stale-name fallback so a mid-rotation exercise never renders nothing.
// ---------------------------------------------------------------------------

export type RampDisplay =
  | { kind: 'kg'; sets: { setNumber: number; kg: number; reps: number }[] }
  | { kind: 'bodyweight'; sets: { setNumber: number; reps: number }[] }
  | { kind: 'stale' }

/**
 * Percent-based (RampSet.load_percent is relative to THIS week's
 * suggested_load_kg, not a stored absolute), so this recomputes fresh every
 * call rather than trusting a cached kg value — correct automatically as
 * suggested_load_kg changes week to week. Every kg step is floored at the
 * equipment's real loadable minimum so "0% of working weight" never
 * displays as an unsafe 0kg.
 */
export function formatRampSets(ex: Exercise): RampDisplay | null {
  if (!ex.ramp_up) return null
  if (ex.ramp_up.exercise !== ex.name) return { kind: 'stale' }
  if (!Array.isArray(ex.ramp_up.sets) || ex.ramp_up.sets.length === 0) return null
  const entry = getExerciseEntry(ex.name)
  if (!entry) return null
  if (ex.suggested_load_kg == null) {
    return { kind: 'bodyweight', sets: ex.ramp_up.sets.map(s => ({ setNumber: s.set_number, reps: s.reps })) }
  }
  const mode = loadingMode(entry)
  const floor = getEquipmentFloorKg(entry)
  return {
    kind: 'kg',
    sets: ex.ramp_up.sets.map(s => ({
      setNumber: s.set_number,
      kg: roundToPlate(Math.max((ex.suggested_load_kg! * s.load_percent) / 100, floor), mode),
      reps: s.reps,
    })),
  }
}

// ---------------------------------------------------------------------------
// Superset grouping (§3.4) — partitions a day's exercise list into singles
// and fused superset groups, preserving each member's ORIGINAL array index.
// mesocycle-edit's swapExerciseInMesocycle addresses exercises positionally
// (currentWeekNumber, dayName, exIndex) — grouping must never lose that.
// ---------------------------------------------------------------------------

export type ExerciseGroup =
  | { kind: 'single'; ex: Exercise; exIndex: number }
  | { kind: 'superset'; label: string; members: { ex: Exercise; exIndex: number }[] }

export function groupExercises(exercises: Exercise[]): ExerciseGroup[] {
  const groups: ExerciseGroup[] = []
  const consumed = new Set<number>()

  exercises.forEach((ex, exIndex) => {
    if (consumed.has(exIndex)) return

    if (!ex.superset_label) {
      groups.push({ kind: 'single', ex, exIndex })
      consumed.add(exIndex)
      return
    }

    // superset_label is 'A1'/'A2'-shaped (exercise-plan.ts) — the leading
    // letter identifies the pair; the trailing digit orders them.
    const letter = ex.superset_label[0]
    const members: { ex: Exercise; exIndex: number }[] = []
    exercises.forEach((candidate, candidateIndex) => {
      if (consumed.has(candidateIndex)) return
      if (candidate.superset_label?.[0] === letter) {
        members.push({ ex: candidate, exIndex: candidateIndex })
        consumed.add(candidateIndex)
      }
    })
    members.sort((a, b) => (a.ex.superset_label ?? '').localeCompare(b.ex.superset_label ?? ''))

    if (members.length >= 2) {
      groups.push({ kind: 'superset', label: letter, members })
    } else if (members.length === 1) {
      // An orphaned single-member label — clearOrphanedSupersetLabels
      // (mesocycle-edit.ts) normally strips this after a swap breaks a
      // pair, but render defensively as a single rather than a one-member
      // "superset" if it's ever seen mid-transition.
      groups.push({ kind: 'single', ex: members[0].ex, exIndex: members[0].exIndex })
    }
  })

  return groups
}

// ---------------------------------------------------------------------------
// THE DAY'S ANCHOR — which exercise is "the main lift" when nothing is tier-1.
//
// 96 of 256 generated days contain no tier_1_primary exercise at all, and the
// split is not subtle: full_gym 0, home_gym 0, minimalist 48 of 64, bodyweight
// 48 of 64. The cause is arithmetic in the catalogue — only 8 of 145 entries
// are tier1_compound and SIX OF THE EIGHT NEED A BARBELL. Without one, the
// only tier-1s reachable are Pull-Ups and Chin-Ups, so a home trainee's pull
// day has a main lift and every squat, press and hinge day has none.
//
// That is behaviour, not decoration: MAIN_LIFT_REST_FLOOR_SECONDS keys on
// tier1_compound, so on those days nothing receives the 60-second floor. The
// round that shipped the floor was called "the day's hardest lift keeps its
// rest"; on 37.5% of days there was nothing for the rule to point at.
//
// ONE DEFINITION, TWO CONSUMERS. The engine needs it to floor the rest; the
// screens need it to print MAIN LIFT. Both read this. It lives here because
// session-derive already owns groupExercises and already imports exercise-db,
// and the engine imports nothing from here — the dependency runs one way.
// ---------------------------------------------------------------------------

/** tier1 beats tier2 beats tier3. Primers and anything unrecognised score 0. */
const ANCHOR_RANK: Record<string, number> = {
  tier1_compound: 3,
  tier2_compound: 2,
  tier3_isolation: 1,
}

/**
 * How "main lift"-ish a movement is, from its mechanics tier alone.
 *
 * Exported because the ENGINE has to rank the same way while it is still
 * holding ExerciseEntry objects (stageTimeCap works on entries, before a day
 * of Exercise rows exists), and the screens rank Exercise rows. Two rankings
 * that agree by coincidence is how the "Main lift" label and the 60-second
 * rest floor would end up on different exercises.
 */
export function anchorRank(mechanicsTier: string | undefined): number {
  return ANCHOR_RANK[String(mechanicsTier)] ?? 0
}

/**
 * The full ordering the anchor is chosen on: tier first, then difficulty
 * within it.
 *
 * Tier is multiplied by 10 so it always dominates — a tier-2 movement can
 * never outrank a tier-1 however hard it is, because tier still decides sets,
 * reps and rest and the anchor must not disagree with the prescription. The
 * bump only orders movements the catalogue currently calls equal, which is
 * the entire defect: Pistol Squat Progression and Air Squat are both
 * tier2_compound, so the anchor used to break that tie on list position.
 */
export function anchorScore(mechanicsTier: string | undefined, name: string): number {
  const rank = anchorRank(mechanicsTier)
  return rank === 0 ? 0 : rank * 10 + anchorDifficultyBump(name)
}

/**
 * The day's hardest STANDALONE movement, or undefined when the day already
 * has a real tier-1 (the existing path owns those and promotion must not
 * touch them) or when nothing qualifies.
 *
 * SUPERSET MEMBERS ARE EXCLUDED, and this is the load-bearing exclusion. A
 * promoted anchor earns a 60-second rest floor; a superset prints "alternate
 * — no rest between" directly underneath it. Promoting a paired movement
 * would have the app contradict itself inside one card. 128 of the days
 * measured had their hardest movement inside a superset, and every one of
 * them keeps no main lift rather than getting a contradictory one — the
 * conservative direction on purpose.
 *
 * Cardio and finishers are excluded because they are not the session's work,
 * and primers because a warm-up movement is never the point of the day.
 */
export function dayAnchorExercise(exercises: Exercise[]): Exercise | undefined {
  // A day with a genuine tier-1 needs no promotion — say so by returning
  // undefined rather than handing back the tier-1 itself, so a caller can
  // never confuse "promoted" with "was always the main lift".
  if (exercises.some(ex => getExerciseEntry(ex.name)?.mechanics_tier === 'tier1_compound')) return undefined

  let best: Exercise | undefined
  let bestRank = 0
  for (const group of groupExercises(exercises)) {
    if (group.kind !== 'single') continue
    const ex = group.ex
    const entry = getExerciseEntry(ex.name)
    if (!entry || entry.mechanics_tier === 'primer') continue
    if (ex.prescription_type === 'steady_state' || ex.tier === 'tier_4_finisher') continue
    // Tier THEN difficulty. Before this carried the difficulty half, a day
    // holding both a Pistol Squat and an Air Squat picked whichever the
    // generator happened to list first — they are the same tier, and the
    // catalogue has no other way to tell them apart.
    const rank = anchorScore(entry.mechanics_tier, ex.name)
    // Strictly greater: genuine ties still go to the earlier exercise, which
    // is the order the generator already put them in.
    if (rank > bestRank) { bestRank = rank; best = ex }
  }
  return best
}

/**
 * Which GROUP index carries the "Main lift" label — the real tier-1 if the
 * day has one, otherwise the promoted anchor. -1 when neither exists.
 *
 * Shared because TodayPanel and PeekPanel each had their own copy of the
 * tier-1 findIndex. That duplication is exactly the shape that let the
 * superset chrome drift between those two screens until a screenshot caught
 * it; one definition means the promotion cannot land on one screen only.
 */
export function mainLiftGroupIndex(groups: ExerciseGroup[], exercises: Exercise[]): number {
  const real = groups.findIndex(g => g.kind === 'single' && g.ex.tier === 'tier_1_primary')
  if (real !== -1) return real
  const anchor = dayAnchorExercise(exercises)
  if (!anchor) return -1
  return groups.findIndex(g => g.kind === 'single' && g.ex === anchor)
}

// ---------------------------------------------------------------------------
// Calibration cue anchor (§1.6.4) — resolves to exactly one exercise row per
// calibration-week day, with a three-step fallback so a known_weight or
// all-bodyweight day still gets the instruction instead of it silently
// disappearing.
// ---------------------------------------------------------------------------

export function resolveCalibrationAnchorIndex(exercises: Exercise[]): number | null {
  if (exercises.length === 0) return null
  const estimateIdx = exercises.findIndex(
    ex => ex.suggested_load_kg != null && isUnverifiedLoadSource(ex.load_source)
  )
  if (estimateIdx !== -1) return estimateIdx
  const anyLoadedIdx = exercises.findIndex(ex => ex.suggested_load_kg != null)
  if (anyLoadedIdx !== -1) return anyLoadedIdx
  return 0
}

// ---------------------------------------------------------------------------
// Set-row numbering (§3.3) — never renumber. The rendered row list is the
// prescribed baseline plus whatever has actually been logged or explicitly
// added, minus anything explicitly removed. `removedSetNumbers` is not
// populated by anything in P2 (the inline today-view grid has no "Remove
// this set" affordance yet — that lands with P3's active mode); the
// parameter exists now so the function's contract already matches what P3
// needs, rather than changing shape later.
// ---------------------------------------------------------------------------

export function computeSetRowNumbers(
  prescribedSets: number,
  loggedSetNumbers: number[],
  extraSetNumbers: number[],
  removedSetNumbers: number[] = [],
): number[] {
  const removed = new Set(removedSetNumbers)
  const rows = new Set<number>()
  for (let i = 1; i <= prescribedSets; i++) {
    if (!removed.has(i)) rows.add(i)
  }
  for (const n of loggedSetNumbers) {
    if (!removed.has(n)) rows.add(n)
  }
  for (const n of extraSetNumbers) {
    if (!removed.has(n)) rows.add(n)
  }
  return Array.from(rows).sort((a, b) => a - b)
}

/**
 * The next number `+ Add set` appends — always past the highest number
 * EVER used for this exercise today, including removed ones, so a removed
 * set's number is never reissued to a different set (the store's
 * natural-key upsert would silently merge them).
 */
export function nextExtraSetNumber(
  prescribedSets: number,
  loggedSetNumbers: number[],
  extraSetNumbers: number[],
): number {
  const everUsed = [
    ...Array.from({ length: prescribedSets }, (_, i) => i + 1),
    ...loggedSetNumbers,
    ...extraSetNumbers,
  ]
  return (everUsed.length > 0 ? Math.max(...everUsed) : prescribedSets) + 1
}

// ---------------------------------------------------------------------------
// Off-plan work union (§1.7 H) — the union of user-declared names and
// detected off-plan logs (chat-logged, swapped-away work). Detected entries
// have no remove affordance; declared entries with zero logged sets can be
// removed by the caller.
// ---------------------------------------------------------------------------

export interface OffPlanWorkItem {
  exerciseId: string
  name: string
  source: 'declared' | 'logged'
}

export function computeOffPlanWork(
  declaredNames: string[],
  logs: ExerciseSetLog[],
  plannedIds: Set<string>,
  getExerciseId: (name: string) => string,
): OffPlanWorkItem[] {
  const byId = new Map<string, OffPlanWorkItem>()
  for (const name of declaredNames) {
    const id = getExerciseId(name)
    byId.set(id, { exerciseId: id, name, source: 'declared' })
  }
  for (const log of logs) {
    const id = log.exercise_id ?? getExerciseId(log.exercise_name)
    if (plannedIds.has(id)) continue
    if (!byId.has(id)) byId.set(id, { exerciseId: id, name: log.exercise_name, source: 'logged' })
  }
  return Array.from(byId.values())
}

// ---------------------------------------------------------------------------
// Completed-set summary text (moved from ExerciseRow.tsx, unchanged) — Part
// 3's exercise-history view needs the identical "30kg × 11, 11, 10"
// formatting for a past session's sets; duplicating it there would be
// exactly the forked-logic pattern this file exists to prevent.
// ---------------------------------------------------------------------------

/** "30kg × 11, 11, 10" for a flat-weight exercise; groups consecutive
 * same-weight sets (ramps) into "25kg × 12 · 30kg × 8"-style segments;
 * "Bodyweight × 11, 11, 10" when nothing was loaded. Accepts anything
 * structurally shaped like the fields it reads, so a history-view row that
 * isn't a full ExerciseSetLog can still be formatted without a cast. */
export function formatCompletedSummary(
  sets: { set_number: number; weight_kg: number; reps_completed: number; is_bodyweight: boolean }[],
): string {
  const ordered = [...sets].sort((a, b) => a.set_number - b.set_number)
  if (ordered.every(s => s.is_bodyweight)) {
    return `Bodyweight × ${ordered.map(s => s.reps_completed).join(', ')}`
  }
  const groups: { weight: number; reps: number[] }[] = []
  for (const s of ordered) {
    const last = groups[groups.length - 1]
    if (last && last.weight === s.weight_kg) last.reps.push(s.reps_completed)
    else groups.push({ weight: s.weight_kg, reps: [s.reps_completed] })
  }
  return groups.map(g => `${g.weight}kg × ${g.reps.join(', ')}`).join(' · ')
}

// ---------------------------------------------------------------------------
// Session summary (Part 1: explicit start/finish) — duration/volume/
// sets-vs-prescribed for one finished session. Pure: takes the day's planned
// exercises and the raw logs, no store/Supabase reads.
// ---------------------------------------------------------------------------

export interface SessionExerciseSummary {
  exerciseId: string
  exerciseName: string
  setsCompleted: number
  setsPrescribed: number
  volumeKg: number
}

export interface SessionSummary {
  durationMinutes: number
  totalVolumeKg: number
  setsCompleted: number
  setsPrescribed: number
  exercises: SessionExerciseSummary[]
}

/**
 * Volume is literally sets × reps × load (weight_kg × reps_completed,
 * summed) — a bodyweight set (weight_kg 0, by SetGrid's own convention)
 * contributes 0, matching how the rest of the app treats bodyweight load.
 * Any logged exercise NOT in `plannedExercises` (off-plan/extra work, same
 * population `computeOffPlanWork` detects) is folded in with
 * setsPrescribed: 0 so the totals still count it honestly.
 */
export function computeSessionSummary(
  logs: ExerciseSetLog[],
  plannedExercises: { id?: string; name: string; sets: number }[],
  startedAtIso: string,
  finishedAtIso: string,
): SessionSummary {
  const exercises: SessionExerciseSummary[] = []
  const accountedIds = new Set<string>()

  for (const planned of plannedExercises) {
    const exerciseId = planned.id ?? planned.name
    const loggedSets = filterLoggableSets(logs, exerciseId, planned.name)
    accountedIds.add(exerciseId)
    if (loggedSets.length === 0 && planned.sets === 0) continue
    exercises.push({
      exerciseId,
      exerciseName: planned.name,
      setsCompleted: loggedSets.length,
      setsPrescribed: planned.sets,
      volumeKg: loggedSets.reduce((sum, s) => sum + s.weight_kg * s.reps_completed, 0),
    })
  }

  const extraByExercise = new Map<string, ExerciseSetLog[]>()
  for (const log of logs) {
    if (log.is_warmup) continue
    const id = log.exercise_id ?? log.exercise_name
    if (accountedIds.has(id)) continue
    const list = extraByExercise.get(id) ?? []
    list.push(log)
    extraByExercise.set(id, list)
  }
  for (const [exerciseId, extraLogs] of extraByExercise) {
    exercises.push({
      exerciseId,
      exerciseName: extraLogs[0].exercise_name,
      setsCompleted: extraLogs.length,
      setsPrescribed: 0,
      volumeKg: extraLogs.reduce((sum, s) => sum + s.weight_kg * s.reps_completed, 0),
    })
  }

  const durationMinutes = Math.max(
    0,
    Math.round((new Date(finishedAtIso).getTime() - new Date(startedAtIso).getTime()) / 60000),
  )

  return {
    durationMinutes,
    totalVolumeKg: exercises.reduce((sum, e) => sum + e.volumeKg, 0),
    setsCompleted: exercises.reduce((sum, e) => sum + e.setsCompleted, 0),
    setsPrescribed: exercises.reduce((sum, e) => sum + e.setsPrescribed, 0),
    exercises,
  }
}
