// ---------------------------------------------------------------------------
// IS THIS WEIGH-IN BELIEVABLE, GIVEN THE LAST ONE?
//
// 9 Oct 2026, the test log's H10. A weigh-in of 62 kg was typed an hour after
// one of 81.2 kg. It was inside the only check there was (25 to 350 kg), so
// it was saved, the 7-day average became 62 and the calorie target dropped
// from 1,689 to 1,506 at once. The missing check is against the LAST weigh-in.
//
// ASHLEY'S RULING, 9 Oct 2026, from three options ("If someone types a weight
// that's far from their last one, what should happen?"): **"Ask, and hold the
// target"** — when a weigh-in is more than about 3% from the last one, ask
// "That's 19 kg lighter than this morning — is 62 right?" and save only on
// yes. Even then, don't move the calorie target until a second day agrees.
//
// This file is the whole of that ruling's arithmetic and its words:
//   checkWeighIn       the verdict on one figure against another;
//   weighInQuestion    whether to ASK before saving, and against what;
//   weighInStanding    which saved weigh-ins the calorie target may follow and
//                      which are HELD until another day agrees with them.
// Every place a weight is typed asks it (the weigh-in card, the Profile weight
// field, and the coach's log_weight through the generated copy in
// supabase/functions/_shared/), and the target reads the standing
// (nutrition-targets.ts), so the three cannot disagree.
//
// NOTHING IS STORED TO MAKE THE HOLD WORK. A held weigh-in is not flagged in
// the database (no column to flag it in, and a flag on one phone would not
// reach another): it is RE-DERIVED from the weigh-ins themselves every time.
// A reading that is surprising against the last one the target trusted waits;
// a later day within a kilo of it releases both.
//
// NO IMPORTS, on purpose: the coach's copy is this file, generated by
// scripts/sync-shared-code.mjs, and has to run on Deno.
// ---------------------------------------------------------------------------

/**
 * How far a weigh-in may sit from the last one before it is surprising, as a
 * share of bodyweight, when both are from the same day.
 *
 * Decided as a strength coach (CSCS delegation), basis: day-to-day bodyweight
 * moves 1-2% on water, food in the gut, salt and glycogen — the same figure
 * the 1 kg target threshold is built on (nutrition-targets.ts). 3% in a day
 * (2.5 kg at 82 kg) is past what that explains, and well short of any typo
 * that drops or swaps a digit.
 */
const WEIGH_IN_SWING_SHARE = 0.03

/**
 * How much more is believable per day since the last weigh-in. The fastest
 * loss or gain a coach would plan is about 1% of bodyweight a week, so 0.15%
 * a day on top of the daily swing. Somebody back after three months is not
 * questioned over 13 kg at 82 kg; somebody back after a year is not
 * questioned at all.
 */
const WEIGH_IN_DRIFT_SHARE_PER_DAY = 0.0015

export type WeighInCheck =
  | { verdict: 'ok' }
  | {
      verdict: 'surprising'
      /** new minus last, in kg, to one decimal: negative is lighter. */
      differenceKg: number
      /** The most that would have been believed, in kg, to one decimal. */
      allowedKg: number
    }

const oneDecimal = (n: number) => Math.round(n * 10) / 10

/**
 * @param newKg      the weight just typed
 * @param lastKg     the weigh-in before it; null or undefined when there is none (then there is nothing to be surprised against)
 * @param daysSince  whole days between the two; 0 for the same day. Unknown is treated as 0, the strictest reading.
 */
export function checkWeighIn(newKg: number, lastKg: number | null | undefined, daysSince: number | null | undefined): WeighInCheck {
  if (!Number.isFinite(newKg) || lastKg == null || !Number.isFinite(lastKg) || lastKg <= 0) return { verdict: 'ok' }
  const days = daysSince != null && Number.isFinite(daysSince) && daysSince > 0 ? daysSince : 0
  const allowedKg = lastKg * (WEIGH_IN_SWING_SHARE + WEIGH_IN_DRIFT_SHARE_PER_DAY * days)
  const differenceKg = newKg - lastKg
  if (Math.abs(differenceKg) <= allowedKg) return { verdict: 'ok' }
  return { verdict: 'surprising', differenceKg: oneDecimal(differenceKg), allowedKg: oneDecimal(allowedKg) }
}

/** Whole calendar days from `earlier` to `later`, both YYYY-MM-DD. Counted on the calendar, not in 24-hour blocks, so a clock change cannot make one day read as none or two. */
export function calendarDaysBetween(earlier: string, later: string): number {
  const utc = (d: string) => { const [y, m, day] = d.split('-').map(Number); return Date.UTC(y, (m ?? 1) - 1, day ?? 1) }
  return Math.round((utc(later) - utc(earlier)) / 86_400_000)
}

// ---------------------------------------------------------------------------
// THE HOLD: which weigh-ins the calorie target may follow.
// ---------------------------------------------------------------------------

export interface WeighInReading {
  /** YYYY-MM-DD */
  date: string
  kg: number
}

/**
 * Two weigh-ins on different days "agree" when they are less than this far
 * apart — the same 1 kg the target rule itself treats as nothing having
 * changed (TARGET_WEIGHT_ANCHOR_THRESHOLD_KG in nutrition-targets.ts; a gate
 * holds the two equal, because this file may not import).
 */
export const WEIGH_IN_AGREES_WITHIN_KG = 1

export interface HeldWeighIn extends WeighInReading {
  /** What it was surprising against: the last weigh-in the target trusted, or the weight the target was last set from. */
  against: WeighInReading
  differenceKg: number
}

export interface WeighInStanding {
  /** Oldest first. The calorie target's 7-day average is taken over these and no others. */
  trusted: WeighInReading[]
  /** Saved and shown like any other weigh-in, but waiting for another day to agree before the target may follow. */
  held: HeldWeighIn[]
}

/**
 * Sort the saved weigh-ins into the ones the target may follow and the ones
 * that are waiting.
 *
 * Walked oldest to newest, keeping "the last weigh-in the target trusted":
 *   - a reading that is believable against it is trusted and becomes it;
 *   - a reading that is surprising against it WAITS;
 *   - a later DAY within a kilo of the waiting one releases both — that is
 *     the "second day agrees" of the ruling;
 *   - a later day that goes back to where the trusted ones were leaves the
 *     waiting one held for good (it was the typo).
 *
 * `anchors` are the weights the target has been set from (one per recorded
 * target, any order). The newest one not later than the oldest reading is
 * where the walk starts, so the very first weigh-in after sign-up has
 * something to be surprising against — a same-day weigh-in REPLACES the
 * sign-up row, and without this a 62 kg typo an hour after signing up at
 * 82 kg would be the only reading there is. With no such anchor the oldest
 * reading is taken as it stands.
 *
 * `readings`: one per date (a later entry for a date replaces an earlier
 * one), any order.
 */
export function weighInStanding(readings: readonly WeighInReading[], anchors?: readonly WeighInReading[] | null): WeighInStanding {
  const byDate = new Map<string, number>()
  for (const r of readings) if (Number.isFinite(r.kg) && r.kg > 0) byDate.set(r.date, r.kg)
  const sorted = [...byDate.entries()].map(([date, kg]) => ({ date, kg })).sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0))
  const trusted: WeighInReading[] = []
  const held: HeldWeighIn[] = []
  if (sorted.length === 0) return { trusted, held }

  let reference: WeighInReading | null = null
  for (const a of anchors ?? []) {
    if (!Number.isFinite(a.kg) || a.kg <= 0 || a.date > sorted[0].date) continue
    if (reference == null || a.date >= reference.date) reference = { date: a.date, kg: a.kg }
  }

  let waiting: HeldWeighIn | null = null
  for (const r of sorted) {
    // `r` is always a LATER day than the one waiting: there is one reading per
    // date and they are walked in order, so a second figure typed the same day
    // replaces the waiting one rather than agreeing with it.
    if (waiting && Math.abs(r.kg - waiting.kg) < WEIGH_IN_AGREES_WITHIN_KG) {
      trusted.push({ date: waiting.date, kg: waiting.kg }, r)
      reference = r
      waiting = null
      continue
    }
    if (reference == null) { trusted.push(r); reference = r; continue }
    const verdict = checkWeighIn(r.kg, reference.kg, calendarDaysBetween(reference.date, r.date))
    if (verdict.verdict === 'ok') {
      trusted.push(r)
      reference = r
      if (waiting) { held.push(waiting); waiting = null }
      continue
    }
    if (waiting) held.push(waiting)
    waiting = { date: r.date, kg: r.kg, against: reference, differenceKg: verdict.differenceKg }
  }
  if (waiting) held.push(waiting)
  return { trusted, held }
}

/** The weigh-in that is waiting on `date`, if that day's is one. */
export function heldWeighInOn(standing: WeighInStanding, date: string): HeldWeighIn | null {
  return standing.held.find(h => h.date === date) ?? null
}

// ---------------------------------------------------------------------------
// THE QUESTION: asked before a surprising weigh-in is saved.
// ---------------------------------------------------------------------------

export interface WeighInQuestion {
  /** new minus the figure it is compared with, kg, one decimal: negative is lighter. */
  differenceKg: number
  /** The figure it is compared with. */
  againstKg: number
  /** Whole days since that figure; 0 is today. */
  daysSince: number
}

/**
 * Whether to ask before saving `newKg` as the weigh-in for `today`, and what
 * to compare it with in the question. Null: save it without asking.
 *
 * Asked when it is surprising against the LAST weigh-in — which, an hour
 * after another, is today's own row (Ashley's example: "lighter than this
 * morning"). And asked when it is fine against that but would still be HELD
 * (surprising against the last weigh-in the target trusted), so that nothing
 * is ever held without her having been asked about it.
 *
 * `readings` are the weigh-ins already saved, today's included if there is
 * one. Same `anchors` as weighInStanding.
 */
export function weighInQuestion(newKg: number, today: string, readings: readonly WeighInReading[], anchors?: readonly WeighInReading[] | null): WeighInQuestion | null {
  if (!Number.isFinite(newKg)) return null
  const upToToday = readings.filter(r => Number.isFinite(r.kg) && r.kg > 0 && r.date <= today)
  let last: WeighInReading | null = null
  for (const r of upToToday) if (last == null || r.date >= last.date) last = r
  if (last) {
    const days = calendarDaysBetween(last.date, today)
    const verdict = checkWeighIn(newKg, last.kg, days)
    if (verdict.verdict === 'surprising') return { differenceKg: verdict.differenceKg, againstKg: last.kg, daysSince: days }
  }
  const after = weighInStanding([...upToToday.filter(r => r.date !== today), { date: today, kg: newKg }], anchors)
  const waiting = heldWeighInOn(after, today)
  if (!waiting) return null
  return { differenceKg: waiting.differenceKg, againstKg: waiting.against.kg, daysSince: Math.max(0, calendarDaysBetween(waiting.against.date, today)) }
}

/** "19.2" / "19": a kilogram figure the way the app prints one — no trailing ".0". */
const kgText = (n: number) => String(oneDecimal(Math.abs(n)))

/** How long ago the figure in the question was, in plain words. */
function sinceWords(daysSince: number): string {
  if (daysSince <= 0) return 'earlier today'
  if (daysSince === 1) return 'yesterday'
  if (daysSince < 14) return `your last weigh-in ${daysSince} days ago`
  if (daysSince < 60) return `your last weigh-in ${Math.round(daysSince / 7)} weeks ago`
  return `your last weigh-in ${Math.round(daysSince / 30)} months ago`
}

/**
 * The question, in the app's words. Ashley's example was "That's 19 kg
 * lighter than this morning — is 62 right?". Two things differ, on purpose:
 * the app does not store what time of day a weigh-in was typed, so it says
 * "earlier today" rather than claim a morning; and the difference keeps its
 * decimal (2.6 kg is not "3 kg").
 */
export function weighInQuestionText(question: WeighInQuestion, newKg: number): string {
  const way = question.differenceKg < 0 ? 'lighter' : 'heavier'
  return `That's ${kgText(question.differenceKg)} kg ${way} than ${sinceWords(question.daysSince)} — is ${kgText(newKg)} kg right?`
}

/** The same question for the Profile weight field, where the figure being replaced is "the weight you gave", not a weigh-in on a day. */
export function profileWeightQuestionText(differenceKg: number, previousKg: number, newKg: number): string {
  const way = differenceKg < 0 ? 'lighter' : 'heavier'
  return `That's ${kgText(differenceKg)} kg ${way} than the ${kgText(previousKg)} kg you gave before — is ${kgText(newKg)} kg right?`
}

/** The two answers. One tap each. */
export const weighInYesLabel = (newKg: number) => `Yes, ${kgText(newKg)} kg`
export const WEIGH_IN_NO_LABEL = 'No, change it'

/** Under a weigh-in that is saved and waiting: what happens to the calorie target, and when. */
export function weighInHeldNote(heldKg: number): string {
  return `${kgText(heldKg)} kg is saved. Your calorie target stays where it is for now and will follow once another day's weigh-in agrees.`
}
