// ===========================================================================
// GENERATED FILE — DO NOT EDIT.
//
// This is src/lib/weigh-in-check.ts, copied here by scripts/sync-shared-code.mjs so the edge
// functions (Deno, which cannot import from src/) run the SAME code the app
// does. Change the source, then run:
//
//     npm run sync:shared
//
// A hand edit here is overwritten by the next sync, and test:food-db-parity
// fails for as long as this file differs from what the script would write.
// ===========================================================================

// ---------------------------------------------------------------------------
// IS THIS WEIGH-IN BELIEVABLE, GIVEN THE LAST ONE?
//
// 9 Oct 2026, the test log's H10. A weigh-in of 62 kg was typed an hour after
// one of 81.2 kg. It was inside the only check there was (25 to 350 kg), so
// it was saved, the 7-day average became 62 and the calorie target dropped
// from 1,689 to 1,506 at once. The missing check is against the LAST weigh-in.
//
// This file is that check and nothing else: it gives a VERDICT. What the app
// does with a surprising one — ask first, hold the target for a second day —
// is Ashley's decision and is not made here. Every place a weight is typed
// asks this one function (the weigh-in card, the Profile weight field, and the
// coach's log_weight through the generated copy in
// supabase/functions/_shared/), so the ruling lands in one place when it comes.
//
// NO IMPORTS, on purpose: the coach's copy is this file, generated by
// scripts/sync-shared-code.mjs, and has to run on Deno.
// ---------------------------------------------------------------------------

/**
 * How far a weigh-in may sit from the last one before it is surprising, as a
 * share of bodyweight, when both are from the same day.
 *
 * Decided as a strength coach (CSCS delegation), basis: day-to-day bodyweight
 * moves 1-2% on water, food in the gut, salt and glycogen — the same figure
 * the 1 kg target threshold is built on (nutrition-targets.ts). 3% in a day
 * (2.5 kg at 82 kg) is past what that explains, and well short of any typo
 * that drops or swaps a digit.
 */
const WEIGH_IN_SWING_SHARE = 0.03

/**
 * How much more is believable per day since the last weigh-in. The fastest
 * loss or gain a coach would plan is about 1% of bodyweight a week, so 0.15%
 * a day on top of the daily swing. Somebody back after three months is not
 * questioned over 13 kg at 82 kg; somebody back after a year is not
 * questioned at all.
 */
const WEIGH_IN_DRIFT_SHARE_PER_DAY = 0.0015

export type WeighInCheck =
  | { verdict: 'ok' }
  | {
      verdict: 'surprising'
      /** new minus last, in kg, to one decimal: negative is lighter. */
      differenceKg: number
      /** The most that would have been believed, in kg, to one decimal. */
      allowedKg: number
    }

const oneDecimal = (n: number) => Math.round(n * 10) / 10

/**
 * @param newKg      the weight just typed
 * @param lastKg     the weigh-in before it; null or undefined when there is none (then there is nothing to be surprised against)
 * @param daysSince  whole days between the two; 0 for the same day. Unknown is treated as 0, the strictest reading.
 */
export function checkWeighIn(newKg: number, lastKg: number | null | undefined, daysSince: number | null | undefined): WeighInCheck {
  if (!Number.isFinite(newKg) || lastKg == null || !Number.isFinite(lastKg) || lastKg <= 0) return { verdict: 'ok' }
  const days = daysSince != null && Number.isFinite(daysSince) && daysSince > 0 ? daysSince : 0
  const allowedKg = lastKg * (WEIGH_IN_SWING_SHARE + WEIGH_IN_DRIFT_SHARE_PER_DAY * days)
  const differenceKg = newKg - lastKg
  if (Math.abs(differenceKg) <= allowedKg) return { verdict: 'ok' }
  return { verdict: 'surprising', differenceKg: oneDecimal(differenceKg), allowedKg: oneDecimal(allowedKg) }
}

/** Whole calendar days from `earlier` to `later`, both YYYY-MM-DD. Counted on the calendar, not in 24-hour blocks, so a clock change cannot make one day read as none or two. */
export function calendarDaysBetween(earlier: string, later: string): number {
  const utc = (d: string) => { const [y, m, day] = d.split('-').map(Number); return Date.UTC(y, (m ?? 1) - 1, day ?? 1) }
  return Math.round((utc(later) - utc(earlier)) / 86_400_000)
}
