/**
 * READ-ONLY audit: how many persisted plans hold a load above its
 * implement's realistic ceiling.
 *
 * Why this exists: the per-implement ceiling (LOADING_CEILING_KG_PER_HAND_
 * OR_TOTAL, load-prescription.ts) only landed on 2026-08-12. Every
 * mesocycle generated before that has UNCAPPED numbers already written to
 * mesocycle_weeks — a code fix does not retroactively clean stored rows, so
 * those plans keep displaying whatever they saved until they are either
 * regenerated by the user or backfilled.
 *
 * This script only SELECTs. It never writes. Run it against production with:
 *
 *   AUDIT_SUPABASE_URL=... AUDIT_SUPABASE_KEY=... npx tsx scripts/count-preceiling-loads.ts
 *
 * Falls back to .env.local (TEST) when those aren't set, so it can be
 * validated safely before ever being pointed at production.
 */
import * as fs from 'fs'
import * as path from 'path'
import { createClient } from '@supabase/supabase-js'
import { getExerciseEntry } from '../src/lib/exercise-db'
import { categorize, getLoadingCeilingKg } from '../src/lib/load-prescription'
import type { MesocycleWeek } from '../src/lib/types'

const envPath = path.join(process.cwd(), '.env.local')
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, 'utf-8').split('\n')) {
    if (line.trim() && !line.startsWith('#')) {
      const [k, v] = line.split('=')
      if (k && v && !process.env[k.trim()]) process.env[k.trim()] = v.trim()
    }
  }
}

const url = process.env.AUDIT_SUPABASE_URL || process.env.VITE_SUPABASE_URL
const key = process.env.AUDIT_SUPABASE_KEY || process.env.VITE_SUPABASE_ANON_KEY
if (!url || !key) { console.error('Need AUDIT_SUPABASE_URL / AUDIT_SUPABASE_KEY (or .env.local).'); process.exit(1) }

async function main() {
  console.log(`Reading (SELECT only) from: ${url!.replace(/https:\/\/([a-z]+)\..*/, 'project=$1')}\n`)
  const supabase = createClient(url!, key!)

  const { data: weeks, error } = await supabase
    .from('mesocycle_weeks')
    .select('profile_id, week_number, days, created_at')
  if (error) { console.error('Query failed:', error.message); process.exit(1) }
  if (!weeks) { console.log('No rows.'); return }

  const affectedProfiles = new Map<string, { slots: number; worst: number; worstName: string }>()
  let totalSlots = 0
  let overCeilingSlots = 0
  const byExercise = new Map<string, { count: number; worst: number; ceiling: number }>()

  for (const row of weeks as { profile_id: string; days: MesocycleWeek['days'] }[]) {
    for (const day of row.days ?? []) {
      for (const ex of day.exercises ?? []) {
        if (ex.suggested_load_kg == null) continue
        totalSlots++
        const entry = getExerciseEntry(ex.name)
        if (!entry) continue
        const ceiling = getLoadingCeilingKg(entry, categorize(entry))
        if (ex.suggested_load_kg <= ceiling) continue

        overCeilingSlots++
        const cur = affectedProfiles.get(row.profile_id) ?? { slots: 0, worst: 0, worstName: '' }
        cur.slots++
        if (ex.suggested_load_kg > cur.worst) { cur.worst = ex.suggested_load_kg; cur.worstName = ex.name }
        affectedProfiles.set(row.profile_id, cur)

        const e = byExercise.get(ex.name) ?? { count: 0, worst: 0, ceiling }
        e.count++
        if (ex.suggested_load_kg > e.worst) e.worst = ex.suggested_load_kg
        byExercise.set(ex.name, e)
      }
    }
  }

  const { count: profileCount } = await supabase
    .from('fitness_profiles').select('*', { count: 'exact', head: true })

  console.log(`fitness_profiles rows:            ${profileCount ?? '?'}`)
  console.log(`mesocycle_weeks rows scanned:     ${weeks.length}`)
  console.log(`loaded exercise slots:            ${totalSlots}`)
  console.log(`slots ABOVE implement ceiling:    ${overCeilingSlots}`)
  console.log(`profiles affected:                ${affectedProfiles.size}\n`)

  if (byExercise.size > 0) {
    console.log('By exercise (worst stored value vs its ceiling):')
    for (const [name, e] of [...byExercise.entries()].sort((a, b) => b[1].count - a[1].count)) {
      console.log(`   ${name.padEnd(30)} ${String(e.count).padStart(5)} slots   worst ${e.worst}kg vs ${e.ceiling}kg ceiling`)
    }
    console.log('\nAffected profiles:')
    for (const [id, p] of [...affectedProfiles.entries()].sort((a, b) => b[1].slots - a[1].slots)) {
      console.log(`   ${id}  ${String(p.slots).padStart(4)} slots   worst ${p.worst}kg (${p.worstName})`)
    }
  } else {
    console.log('No stored load exceeds its implement ceiling.')
  }
}

main().catch(e => { console.error(e); process.exit(1) })
