/*
  # Every table belongs to somebody (audit §1.1, §1.2)

  GENERATED by scripts/generate-rls-migration.mjs from the migrations in this
  directory. Regenerate rather than edit by hand — `node
  scripts/generate-rls-migration.mjs`, and `--check` fails if this file has
  drifted from the schema.

  ## What was wrong

  All 112 policies across 28 tables were `TO anon USING (true)` — anonymous,
  unconditional read, write and delete. The anon key ships inside the app's
  JavaScript because it has to, so anyone who opened the app and copied one
  string could download every user's weight history, injuries, allergies and
  chat transcripts, or delete them.

  That was a deliberate single-tenant decision, and the migration that set
  the pattern says so. It stopped being right when the app got users.

  ## How ownership arrives without locking anyone out

  `fitness_profiles.owner_id` is new and NULL on every existing row. A NULL
  owner is readable by NOBODY — deliberately. The only way to attach one is
  `claim_profile`, a SECURITY DEFINER function that sets owner_id where it is
  still NULL, called by the client once it has signed in (anonymously, with
  no interruption) using the profile id already in its localStorage.

  The tempting alternative — a policy allowing reads where `owner_id IS NULL`
  so a client can find its own row — would leave every unclaimed profile
  readable by anyone, which is the hole this migration exists to close.

  RESIDUAL RISK, ON THE RECORD: someone who knows a specific profile's UUID
  could claim it before its owner next opens the app. That needs a v4 UUID
  that is no longer listable, where today the same person needs nothing at
  all. The window closes per user on their next visit.

  ## Why the drops name policies rather than tables

  chat_messages' policies are called `anon_select_messages`, not
  `anon_select_chat_messages`. Dropping the name a table-driven loop would
  have guessed is a silent no-op, the old `USING (true)` policy survives,
  and permissive policies OR together — so the transcripts would have stayed
  world-readable after the migration that existed to stop that. Every DROP
  below is a policy name read out of the migrations.

  ## Not scoped, on purpose
    - ai_usage_daily: service-role only already; RLS on, no policy. See its own migration.
    - nutrition_cache: a shared ingredient->macros lookup with no user data in it. Left readable so every client does not re-derive the same numbers; writes are closed.
    - fitness_profiles: the root table — scoped on owner_id directly, below.
    - set_logs: CLOSED, not scoped — user_id is text, not a uuid pointing at fitness_profiles — owns_profile() cannot be applied to it. Nothing in src/ reads it.

  ## Safety

  Edge functions use the service-role key and bypass RLS entirely, so none of
  them change. `db:push-both` applies this to TEST first.
*/

-- -------------------------------------------------------------------------
-- 1. Ownership on the root table
-- -------------------------------------------------------------------------

ALTER TABLE fitness_profiles ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_fitness_profiles_owner ON fitness_profiles (owner_id);

-- -------------------------------------------------------------------------
-- 2. One predicate, used by every child policy
-- -------------------------------------------------------------------------
--
-- STABLE so the planner calls it once per query rather than once per row, and
-- SECURITY DEFINER so a child table's policy can consult fitness_profiles
-- without the caller needing to read it directly.

CREATE OR REPLACE FUNCTION owns_profile(p uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM fitness_profiles
    WHERE id = p AND owner_id IS NOT NULL AND owner_id = auth.uid()
  );
$$;

REVOKE ALL ON FUNCTION owns_profile(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION owns_profile(uuid) TO anon, authenticated;

-- -------------------------------------------------------------------------
-- 3. Claiming a legacy profile — the ONLY way an unowned row gets an owner
-- -------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION claim_profile(p_profile_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  claimed integer;
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN false;
  END IF;

  -- `owner_id IS NULL` is what makes this safe to call repeatedly and
  -- impossible to use to steal an owned profile.
  UPDATE fitness_profiles
     SET owner_id = auth.uid()
   WHERE id = p_profile_id
     AND owner_id IS NULL;

  GET DIAGNOSTICS claimed = ROW_COUNT;
  RETURN claimed > 0;
END;
$$;

REVOKE ALL ON FUNCTION claim_profile(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION claim_profile(uuid) TO anon, authenticated;

-- -------------------------------------------------------------------------
-- 4. The root table's own policies
-- -------------------------------------------------------------------------

DROP POLICY IF EXISTS "anon_delete_profiles" ON fitness_profiles;
DROP POLICY IF EXISTS "anon_insert_profiles" ON fitness_profiles;
DROP POLICY IF EXISTS "anon_select_profiles" ON fitness_profiles;
DROP POLICY IF EXISTS "anon_update_profiles" ON fitness_profiles;

CREATE POLICY "owner_select_fitness_profiles" ON fitness_profiles FOR SELECT
  TO anon, authenticated USING (owner_id IS NOT NULL AND owner_id = auth.uid());

-- A new profile must be stamped with its creator. WITH CHECK makes it
-- impossible to insert one owned by somebody else.
CREATE POLICY "owner_insert_fitness_profiles" ON fitness_profiles FOR INSERT
  TO anon, authenticated WITH CHECK (owner_id = auth.uid());

CREATE POLICY "owner_update_fitness_profiles" ON fitness_profiles FOR UPDATE
  TO anon, authenticated
  USING (owner_id IS NOT NULL AND owner_id = auth.uid())
  WITH CHECK (owner_id = auth.uid());

CREATE POLICY "owner_delete_fitness_profiles" ON fitness_profiles FOR DELETE
  TO anon, authenticated USING (owner_id IS NOT NULL AND owner_id = auth.uid());

-- -------------------------------------------------------------------------
-- 5. Every child table (25 of them), scoped through owns_profile
-- -------------------------------------------------------------------------

-- cardio_logs (keys on user_id)
DROP POLICY IF EXISTS "anon_delete_cardio_logs" ON cardio_logs;
DROP POLICY IF EXISTS "anon_insert_cardio_logs" ON cardio_logs;
DROP POLICY IF EXISTS "anon_select_cardio_logs" ON cardio_logs;
DROP POLICY IF EXISTS "anon_update_cardio_logs" ON cardio_logs;
ALTER TABLE cardio_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_cardio_logs" ON cardio_logs FOR SELECT
  TO anon, authenticated USING (owns_profile(user_id));
CREATE POLICY "owner_insert_cardio_logs" ON cardio_logs FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(user_id));
CREATE POLICY "owner_update_cardio_logs" ON cardio_logs FOR UPDATE
  TO anon, authenticated USING (owns_profile(user_id)) WITH CHECK (owns_profile(user_id));
CREATE POLICY "owner_delete_cardio_logs" ON cardio_logs FOR DELETE
  TO anon, authenticated USING (owns_profile(user_id));

-- chat_messages (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_messages" ON chat_messages;
DROP POLICY IF EXISTS "anon_insert_messages" ON chat_messages;
DROP POLICY IF EXISTS "anon_select_messages" ON chat_messages;
DROP POLICY IF EXISTS "anon_update_messages" ON chat_messages;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_chat_messages" ON chat_messages FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_chat_messages" ON chat_messages FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_chat_messages" ON chat_messages FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_chat_messages" ON chat_messages FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- daily_metrics (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_daily_metrics" ON daily_metrics;
DROP POLICY IF EXISTS "anon_insert_daily_metrics" ON daily_metrics;
DROP POLICY IF EXISTS "anon_select_daily_metrics" ON daily_metrics;
DROP POLICY IF EXISTS "anon_update_daily_metrics" ON daily_metrics;
ALTER TABLE daily_metrics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_daily_metrics" ON daily_metrics FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_daily_metrics" ON daily_metrics FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_daily_metrics" ON daily_metrics FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_daily_metrics" ON daily_metrics FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- daily_nutrition_targets (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_daily_nutrition_targets" ON daily_nutrition_targets;
DROP POLICY IF EXISTS "anon_insert_daily_nutrition_targets" ON daily_nutrition_targets;
DROP POLICY IF EXISTS "anon_select_daily_nutrition_targets" ON daily_nutrition_targets;
DROP POLICY IF EXISTS "anon_update_daily_nutrition_targets" ON daily_nutrition_targets;
ALTER TABLE daily_nutrition_targets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_daily_nutrition_targets" ON daily_nutrition_targets FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_daily_nutrition_targets" ON daily_nutrition_targets FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_daily_nutrition_targets" ON daily_nutrition_targets FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_daily_nutrition_targets" ON daily_nutrition_targets FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- daily_steps (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_daily_steps" ON daily_steps;
DROP POLICY IF EXISTS "anon_insert_daily_steps" ON daily_steps;
DROP POLICY IF EXISTS "anon_select_daily_steps" ON daily_steps;
DROP POLICY IF EXISTS "anon_update_daily_steps" ON daily_steps;
ALTER TABLE daily_steps ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_daily_steps" ON daily_steps FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_daily_steps" ON daily_steps FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_daily_steps" ON daily_steps FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_daily_steps" ON daily_steps FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- exercise_plans (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_exercise_plans" ON exercise_plans;
DROP POLICY IF EXISTS "anon_insert_exercise_plans" ON exercise_plans;
DROP POLICY IF EXISTS "anon_select_exercise_plans" ON exercise_plans;
DROP POLICY IF EXISTS "anon_update_exercise_plans" ON exercise_plans;
ALTER TABLE exercise_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_exercise_plans" ON exercise_plans FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_exercise_plans" ON exercise_plans FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_exercise_plans" ON exercise_plans FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_exercise_plans" ON exercise_plans FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- exercise_set_logs (keys on user_id)
DROP POLICY IF EXISTS "anon_delete_exercise_set_logs" ON exercise_set_logs;
DROP POLICY IF EXISTS "anon_insert_exercise_set_logs" ON exercise_set_logs;
DROP POLICY IF EXISTS "anon_select_exercise_set_logs" ON exercise_set_logs;
DROP POLICY IF EXISTS "anon_update_exercise_set_logs" ON exercise_set_logs;
ALTER TABLE exercise_set_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_exercise_set_logs" ON exercise_set_logs FOR SELECT
  TO anon, authenticated USING (owns_profile(user_id));
CREATE POLICY "owner_insert_exercise_set_logs" ON exercise_set_logs FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(user_id));
CREATE POLICY "owner_update_exercise_set_logs" ON exercise_set_logs FOR UPDATE
  TO anon, authenticated USING (owns_profile(user_id)) WITH CHECK (owns_profile(user_id));
CREATE POLICY "owner_delete_exercise_set_logs" ON exercise_set_logs FOR DELETE
  TO anon, authenticated USING (owns_profile(user_id));

-- favorite_meals (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_favorite_meals" ON favorite_meals;
DROP POLICY IF EXISTS "anon_insert_favorite_meals" ON favorite_meals;
DROP POLICY IF EXISTS "anon_select_favorite_meals" ON favorite_meals;
DROP POLICY IF EXISTS "anon_update_favorite_meals" ON favorite_meals;
ALTER TABLE favorite_meals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_favorite_meals" ON favorite_meals FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_favorite_meals" ON favorite_meals FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_favorite_meals" ON favorite_meals FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_favorite_meals" ON favorite_meals FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- grocery_items (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_grocery_items" ON grocery_items;
DROP POLICY IF EXISTS "anon_insert_grocery_items" ON grocery_items;
DROP POLICY IF EXISTS "anon_select_grocery_items" ON grocery_items;
DROP POLICY IF EXISTS "anon_update_grocery_items" ON grocery_items;
ALTER TABLE grocery_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_grocery_items" ON grocery_items FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_grocery_items" ON grocery_items FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_grocery_items" ON grocery_items FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_grocery_items" ON grocery_items FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- load_suggestions (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_load_suggestions" ON load_suggestions;
DROP POLICY IF EXISTS "anon_insert_load_suggestions" ON load_suggestions;
DROP POLICY IF EXISTS "anon_select_load_suggestions" ON load_suggestions;
DROP POLICY IF EXISTS "anon_update_load_suggestions" ON load_suggestions;
ALTER TABLE load_suggestions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_load_suggestions" ON load_suggestions FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_load_suggestions" ON load_suggestions FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_load_suggestions" ON load_suggestions FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_load_suggestions" ON load_suggestions FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- meal_events (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_meal_events" ON meal_events;
DROP POLICY IF EXISTS "anon_insert_meal_events" ON meal_events;
DROP POLICY IF EXISTS "anon_select_meal_events" ON meal_events;
DROP POLICY IF EXISTS "anon_update_meal_events" ON meal_events;
ALTER TABLE meal_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_meal_events" ON meal_events FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_meal_events" ON meal_events FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_meal_events" ON meal_events FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_meal_events" ON meal_events FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- meal_plan_picks (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_meal_plan_picks" ON meal_plan_picks;
DROP POLICY IF EXISTS "anon_insert_meal_plan_picks" ON meal_plan_picks;
DROP POLICY IF EXISTS "anon_select_meal_plan_picks" ON meal_plan_picks;
DROP POLICY IF EXISTS "anon_update_meal_plan_picks" ON meal_plan_picks;
ALTER TABLE meal_plan_picks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_meal_plan_picks" ON meal_plan_picks FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_meal_plan_picks" ON meal_plan_picks FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_meal_plan_picks" ON meal_plan_picks FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_meal_plan_picks" ON meal_plan_picks FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- meal_plan_slots (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_meal_plan_slots" ON meal_plan_slots;
DROP POLICY IF EXISTS "anon_insert_meal_plan_slots" ON meal_plan_slots;
DROP POLICY IF EXISTS "anon_select_meal_plan_slots" ON meal_plan_slots;
DROP POLICY IF EXISTS "anon_update_meal_plan_slots" ON meal_plan_slots;
ALTER TABLE meal_plan_slots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_meal_plan_slots" ON meal_plan_slots FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_meal_plan_slots" ON meal_plan_slots FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_meal_plan_slots" ON meal_plan_slots FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_meal_plan_slots" ON meal_plan_slots FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- meal_plans (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_meal_plans" ON meal_plans;
DROP POLICY IF EXISTS "anon_insert_meal_plans" ON meal_plans;
DROP POLICY IF EXISTS "anon_select_meal_plans" ON meal_plans;
DROP POLICY IF EXISTS "anon_update_meal_plans" ON meal_plans;
ALTER TABLE meal_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_meal_plans" ON meal_plans FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_meal_plans" ON meal_plans FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_meal_plans" ON meal_plans FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_meal_plans" ON meal_plans FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- mesocycle_weeks (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_mesocycle_weeks" ON mesocycle_weeks;
DROP POLICY IF EXISTS "anon_insert_mesocycle_weeks" ON mesocycle_weeks;
DROP POLICY IF EXISTS "anon_select_mesocycle_weeks" ON mesocycle_weeks;
DROP POLICY IF EXISTS "anon_update_mesocycle_weeks" ON mesocycle_weeks;
ALTER TABLE mesocycle_weeks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_mesocycle_weeks" ON mesocycle_weeks FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_mesocycle_weeks" ON mesocycle_weeks FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_mesocycle_weeks" ON mesocycle_weeks FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_mesocycle_weeks" ON mesocycle_weeks FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- pending_actions (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_pending_actions" ON pending_actions;
DROP POLICY IF EXISTS "anon_insert_pending_actions" ON pending_actions;
DROP POLICY IF EXISTS "anon_select_pending_actions" ON pending_actions;
DROP POLICY IF EXISTS "anon_update_pending_actions" ON pending_actions;
ALTER TABLE pending_actions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_pending_actions" ON pending_actions FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_pending_actions" ON pending_actions FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_pending_actions" ON pending_actions FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_pending_actions" ON pending_actions FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- plan_adaptations (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_plan_adaptations" ON plan_adaptations;
DROP POLICY IF EXISTS "anon_insert_plan_adaptations" ON plan_adaptations;
DROP POLICY IF EXISTS "anon_select_plan_adaptations" ON plan_adaptations;
DROP POLICY IF EXISTS "anon_update_plan_adaptations" ON plan_adaptations;
ALTER TABLE plan_adaptations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_plan_adaptations" ON plan_adaptations FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_plan_adaptations" ON plan_adaptations FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_plan_adaptations" ON plan_adaptations FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_plan_adaptations" ON plan_adaptations FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- user_context_facts (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_user_context_facts" ON user_context_facts;
DROP POLICY IF EXISTS "anon_insert_user_context_facts" ON user_context_facts;
DROP POLICY IF EXISTS "anon_select_user_context_facts" ON user_context_facts;
DROP POLICY IF EXISTS "anon_update_user_context_facts" ON user_context_facts;
ALTER TABLE user_context_facts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_user_context_facts" ON user_context_facts FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_user_context_facts" ON user_context_facts FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_user_context_facts" ON user_context_facts FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_user_context_facts" ON user_context_facts FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- user_facts (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_user_facts" ON user_facts;
DROP POLICY IF EXISTS "anon_insert_user_facts" ON user_facts;
DROP POLICY IF EXISTS "anon_select_user_facts" ON user_facts;
DROP POLICY IF EXISTS "anon_update_user_facts" ON user_facts;
ALTER TABLE user_facts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_user_facts" ON user_facts FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_user_facts" ON user_facts FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_user_facts" ON user_facts FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_user_facts" ON user_facts FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- user_goals (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_user_goals" ON user_goals;
DROP POLICY IF EXISTS "anon_insert_user_goals" ON user_goals;
DROP POLICY IF EXISTS "anon_select_user_goals" ON user_goals;
DROP POLICY IF EXISTS "anon_update_user_goals" ON user_goals;
ALTER TABLE user_goals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_user_goals" ON user_goals FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_user_goals" ON user_goals FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_user_goals" ON user_goals FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_user_goals" ON user_goals FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- water_logs (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_water_logs" ON water_logs;
DROP POLICY IF EXISTS "anon_insert_water_logs" ON water_logs;
DROP POLICY IF EXISTS "anon_select_water_logs" ON water_logs;
DROP POLICY IF EXISTS "anon_update_water_logs" ON water_logs;
ALTER TABLE water_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_water_logs" ON water_logs FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_water_logs" ON water_logs FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_water_logs" ON water_logs FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_water_logs" ON water_logs FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- weight_basis_offers (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_weight_basis_offers" ON weight_basis_offers;
DROP POLICY IF EXISTS "anon_insert_weight_basis_offers" ON weight_basis_offers;
DROP POLICY IF EXISTS "anon_select_weight_basis_offers" ON weight_basis_offers;
DROP POLICY IF EXISTS "anon_update_weight_basis_offers" ON weight_basis_offers;
ALTER TABLE weight_basis_offers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_weight_basis_offers" ON weight_basis_offers FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_weight_basis_offers" ON weight_basis_offers FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_weight_basis_offers" ON weight_basis_offers FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_weight_basis_offers" ON weight_basis_offers FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- workout_logs (keys on user_id)
DROP POLICY IF EXISTS "anon_delete_workout_logs" ON workout_logs;
DROP POLICY IF EXISTS "anon_insert_workout_logs" ON workout_logs;
DROP POLICY IF EXISTS "anon_select_workout_logs" ON workout_logs;
DROP POLICY IF EXISTS "anon_update_workout_logs" ON workout_logs;
ALTER TABLE workout_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_workout_logs" ON workout_logs FOR SELECT
  TO anon, authenticated USING (owns_profile(user_id));
CREATE POLICY "owner_insert_workout_logs" ON workout_logs FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(user_id));
CREATE POLICY "owner_update_workout_logs" ON workout_logs FOR UPDATE
  TO anon, authenticated USING (owns_profile(user_id)) WITH CHECK (owns_profile(user_id));
CREATE POLICY "owner_delete_workout_logs" ON workout_logs FOR DELETE
  TO anon, authenticated USING (owns_profile(user_id));

-- workout_sessions (keys on profile_id)
DROP POLICY IF EXISTS "anon_delete_workout_sessions" ON workout_sessions;
DROP POLICY IF EXISTS "anon_insert_workout_sessions" ON workout_sessions;
DROP POLICY IF EXISTS "anon_select_workout_sessions" ON workout_sessions;
DROP POLICY IF EXISTS "anon_update_workout_sessions" ON workout_sessions;
ALTER TABLE workout_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_workout_sessions" ON workout_sessions FOR SELECT
  TO anon, authenticated USING (owns_profile(profile_id));
CREATE POLICY "owner_insert_workout_sessions" ON workout_sessions FOR INSERT
  TO anon, authenticated WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_update_workout_sessions" ON workout_sessions FOR UPDATE
  TO anon, authenticated USING (owns_profile(profile_id)) WITH CHECK (owns_profile(profile_id));
CREATE POLICY "owner_delete_workout_sessions" ON workout_sessions FOR DELETE
  TO anon, authenticated USING (owns_profile(profile_id));

-- workout_exercises has no profile column of its own — scoped through its parent, workout_sessions.
DROP POLICY IF EXISTS "anon_delete_workout_exercises" ON workout_exercises;
DROP POLICY IF EXISTS "anon_insert_workout_exercises" ON workout_exercises;
DROP POLICY IF EXISTS "anon_select_workout_exercises" ON workout_exercises;
DROP POLICY IF EXISTS "anon_update_workout_exercises" ON workout_exercises;
ALTER TABLE workout_exercises ENABLE ROW LEVEL SECURITY;
CREATE POLICY "owner_select_workout_exercises" ON workout_exercises FOR SELECT
  TO anon, authenticated USING (EXISTS (
    SELECT 1 FROM workout_sessions p WHERE p.id = workout_exercises.workout_session_id AND owns_profile(p.profile_id)));
CREATE POLICY "owner_insert_workout_exercises" ON workout_exercises FOR INSERT
  TO anon, authenticated WITH CHECK (EXISTS (
    SELECT 1 FROM workout_sessions p WHERE p.id = workout_exercises.workout_session_id AND owns_profile(p.profile_id)));
CREATE POLICY "owner_update_workout_exercises" ON workout_exercises FOR UPDATE
  TO anon, authenticated USING (EXISTS (
    SELECT 1 FROM workout_sessions p WHERE p.id = workout_exercises.workout_session_id AND owns_profile(p.profile_id))) WITH CHECK (EXISTS (
    SELECT 1 FROM workout_sessions p WHERE p.id = workout_exercises.workout_session_id AND owns_profile(p.profile_id)));
CREATE POLICY "owner_delete_workout_exercises" ON workout_exercises FOR DELETE
  TO anon, authenticated USING (EXISTS (
    SELECT 1 FROM workout_sessions p WHERE p.id = workout_exercises.workout_session_id AND owns_profile(p.profile_id)));

-- -------------------------------------------------------------------------
-- 6. Closed entirely — reachable by the service role only
-- -------------------------------------------------------------------------

-- set_logs: user_id is text, not a uuid pointing at fitness_profiles — owns_profile() cannot be applied to it.
-- RLS on with no policy means anon and authenticated read nothing and write
-- nothing. Edge functions and the dashboard still reach it via service_role,
-- so nothing is destroyed — it stops being readable by anyone with the key
-- that ships in the app.
DROP POLICY IF EXISTS "anon_delete_set_logs" ON set_logs;
DROP POLICY IF EXISTS "anon_insert_set_logs" ON set_logs;
DROP POLICY IF EXISTS "anon_select_set_logs" ON set_logs;
DROP POLICY IF EXISTS "anon_update_set_logs" ON set_logs;
ALTER TABLE set_logs ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------------------
-- 7. nutrition_cache — readable by all, writable by none
-- -------------------------------------------------------------------------
--
-- A shared ingredient->macros lookup holding no user data. Left readable so
-- every client does not re-derive the same numbers; the write policies go, so
-- it can no longer be poisoned by anyone holding the anon key.

DROP POLICY IF EXISTS "anon_delete_nutrition_cache" ON nutrition_cache;
DROP POLICY IF EXISTS "anon_insert_nutrition_cache" ON nutrition_cache;
DROP POLICY IF EXISTS "anon_update_nutrition_cache" ON nutrition_cache;
